from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ColumnSchema:
    name: str
    data_type: str
    description: str
    examples: tuple[str, ...] = ()


@dataclass(frozen=True)
class JoinRule:
    left_table: str
    left_column: str
    right_table: str
    right_column: str
    condition: str
    notes: str = ""


def _fallback_column_schema(column_name: str) -> ColumnSchema:
    explicit_types = {
        "id": "bigint",
        "run_id": "text",
        "symbol": "text",
        "index_symbol": "text",
        "series": "text",
        "source_trail": "jsonb",
        "analysis_json": "jsonb",
        "ratios_snapshot": "jsonb",
        "raw_json": "jsonb",
        "fund_details": "jsonb",
        "key_strengths": "text[]",
        "key_risks": "text[]",
        "hit_target": "boolean",
        "hit_stop": "boolean",
        "acknowledged": "boolean",
        "above_50dma": "boolean",
        "above_200dma": "boolean",
    }
    explicit_descriptions = {
        "id": "Surrogate row identifier.",
        "run_id": "Generated run identifier used to join related report rows.",
        "symbol": "Canonical NSE symbol.",
        "index_symbol": "Index name or symbol.",
        "period_label": "Human-readable reporting period label.",
        "period_end": "Reporting period end date.",
        "period_type": "Reporting period type such as quarter or annual.",
        "revenue": "Reported revenue or sales value.",
        "expenses": "Reported total expenses value.",
        "operating_profit": "Reported operating profit value.",
        "opm_pct": "Operating profit margin percentage.",
        "other_income": "Reported other income value.",
        "interest": "Reported interest expense value.",
        "depreciation": "Reported depreciation and amortization value.",
        "pbt": "Profit before tax value.",
        "tax_pct": "Effective tax percentage.",
        "pat": "Profit after tax value.",
        "eps": "Reported earnings per share.",
        "dividend_payout_pct": "Dividend payout percentage.",
        "equity_capital": "Reported equity share capital.",
        "reserves": "Reported reserves and surplus.",
        "borrowings": "Reported borrowings or debt.",
        "other_liabilities": "Reported other liabilities.",
        "total_liabilities": "Reported total liabilities.",
        "fixed_assets": "Reported fixed assets.",
        "cwip": "Capital work in progress.",
        "investments": "Reported investments.",
        "other_assets": "Reported other assets.",
        "total_assets": "Reported total assets.",
        "net_debt": "Net debt value when calculated or loaded.",
        "operating_cf": "Cash flow from operating activities.",
        "investing_cf": "Cash flow from investing activities.",
        "financing_cf": "Cash flow from financing activities.",
        "net_cf": "Net cash flow for the period.",
        "filing_url": "URL or path for the source filing.",
        "business_summary": "Business summary extracted or generated from evidence.",
        "pl_commentary": "Profit and loss commentary.",
        "bs_commentary": "Balance sheet commentary.",
        "cf_commentary": "Cash-flow commentary.",
        "verdict": "Results verdict label such as beat, inline, miss, mixed, or unknown.",
        "score": "Generated score for ranking or assessment.",
        "report_path": "Generated report file path.",
        "llm_model": "LLM model used for the generated analysis.",
        "date_issued": "Date a trading signal was issued.",
        "signal": "Trading signal label such as BUY, SELL, HOLD, or WATCH.",
        "setup_class": "Setup classification for a generated signal.",
        "entry_low": "Lower bound of entry range.",
        "entry_high": "Upper bound of entry range.",
        "stop_loss": "Stop-loss reference price.",
        "target_1": "First target price.",
        "target_2": "Second target price.",
        "regime_at_issue": "Market regime at signal issue time.",
        "date_resolved": "Date a signal outcome was resolved.",
        "price_at_resolution": "Price when a signal outcome was resolved.",
        "return_pct": "Realized or tracked return percentage.",
        "action_bucket": "Action classification bucket.",
        "action_reason": "Reason attached to the action bucket.",
        "trade_date": "Market trading date.",
        "snapshot_date": "Snapshot date for point-in-time generated data.",
        "event_date": "Corporate event date.",
        "alert_date": "Date associated with an alert.",
        "deal_date": "Bulk or block deal date.",
        "created_at": "Row creation timestamp.",
        "updated_at": "Row update timestamp.",
        "fetched_at": "Source fetch timestamp.",
        "generated_at": "Generation timestamp.",
    }
    if column_name in explicit_types:
        data_type = explicit_types[column_name]
    elif column_name.endswith("_date"):
        data_type = "date"
    elif column_name.endswith("_ts") or column_name.endswith("_at"):
        data_type = "timestamp"
    elif column_name.endswith("_json") or column_name.endswith("_snapshot"):
        data_type = "jsonb"
    elif column_name.startswith("is_") or column_name.startswith("has_"):
        data_type = "boolean"
    elif (
        column_name.endswith("_pct")
        or column_name.endswith("_score")
        or column_name.endswith("_price")
        or column_name.endswith("_cr")
        or column_name
        in {
            "open",
            "high",
            "low",
            "close",
            "volume",
            "qty",
            "price",
            "confidence",
            "rsi",
            "trin",
            "trin_5d",
            "adv_volume",
            "dec_volume",
            "nifty500_close",
            "fii_net_today",
            "dii_net_today",
            "fii_net_5d",
            "dii_net_5d",
        }
    ):
        data_type = "numeric"
    elif column_name.endswith("_count") or column_name in {"rank", "days_in_window", "days_in_regime", "advances", "declines", "unchanged", "net_ad", "total_stocks"}:
        data_type = "integer"
    else:
        data_type = "text"

    description = explicit_descriptions.get(
        column_name,
        f"{column_name.replace('_', ' ').capitalize()} field from the approved Agent Adda schema.",
    )
    return ColumnSchema(name=column_name, data_type=data_type, description=description)


@dataclass(frozen=True)
class TableSchema:
    name: str
    columns: tuple[str, ...]
    description: str
    column_details: tuple[ColumnSchema, ...] = ()
    primary_key: tuple[str, ...] = ()
    latest_date_column: str | None = None
    common_filters: tuple[str, ...] = ()
    value_rules: tuple[str, ...] = ()

    def column_payload(self) -> dict[str, dict[str, object]]:
        by_name = {column.name: column for column in self.column_details}
        payload: dict[str, dict[str, object]] = {}
        for name in self.columns:
            detail = by_name.get(name)
            if detail is None:
                detail = _fallback_column_schema(name)
            item: dict[str, object] = {
                "data_type": detail.data_type,
                "description": detail.description,
            }
            if detail.examples:
                item["examples"] = list(detail.examples)
            payload[name] = item
        return payload


@dataclass(frozen=True)
class SchemaCatalog:
    tables: dict[str, TableSchema]
    join_rules: tuple[JoinRule, ...] = ()
    global_rules: tuple[str, ...] = ()

    def as_prompt_payload(self, table_names: tuple[str, ...] | list[str] | None = None) -> dict[str, dict[str, object]]:
        selected = tuple(table_names or tuple(self.tables))
        selected_set = set(selected)
        payload: dict[str, dict[str, object]] = {
            table_name: {
                "columns": list(self.tables[table_name].columns),
                "column_details": self.tables[table_name].column_payload(),
                "description": self.tables[table_name].description,
                "primary_key": list(self.tables[table_name].primary_key),
                "latest_date_column": self.tables[table_name].latest_date_column,
                "common_filters": list(self.tables[table_name].common_filters),
                "value_rules": list(self.tables[table_name].value_rules),
            }
            for table_name in selected
            if table_name in self.tables
        }
        payload["_join_rules"] = {
            "rules": [
                {
                    "left_table": rule.left_table,
                    "left_column": rule.left_column,
                    "right_table": rule.right_table,
                    "right_column": rule.right_column,
                    "condition": rule.condition,
                    "notes": rule.notes,
                }
                for rule in self.join_rules
                if rule.left_table in selected_set and rule.right_table in selected_set
            ]
        }
        payload["_global_rules"] = {"rules": list(self.global_rules)}
        return payload

    def has_table(self, table_name: str) -> bool:
        return table_name in self.tables

    def has_column(self, table_name: str, column_name: str) -> bool:
        table = self.tables.get(table_name)
        return bool(table and column_name in table.columns)


def default_schema_catalog() -> SchemaCatalog:
    def col(name: str, data_type: str, description: str, *examples: str) -> ColumnSchema:
        return ColumnSchema(name=name, data_type=data_type, description=description, examples=tuple(examples))

    return SchemaCatalog(
        tables={
            "market.equity_eod": TableSchema(
                name="market.equity_eod",
                description="NSE equity EOD OHLCV and derived price context.",
                columns=(
                    "trade_date",
                    "symbol",
                    "series",
                    "open",
                    "high",
                    "low",
                    "close",
                    "last_price",
                    "prev_close",
                    "change_abs",
                    "change_pct",
                    "volume",
                    "turnover_cr",
                    "total_trades",
                    "delivery_qty",
                    "delivery_pct",
                    "week52_high",
                    "week52_low",
                    "market_cap_cr",
                ),
                column_details=(
                    col("trade_date", "date", "EOD trading date for the bar."),
                    col("symbol", "text", "Canonical NSE symbol."),
                    col("series", "text", "NSE series; usually EQ for equity cash market."),
                    col("open", "numeric", "EOD open price."),
                    col("high", "numeric", "EOD high price."),
                    col("low", "numeric", "EOD low price."),
                    col("close", "numeric", "EOD close price; use for returns and trend calculations."),
                    col("last_price", "numeric", "Last traded price from the bhavcopy row."),
                    col("prev_close", "numeric", "Previous close used for 1-day change."),
                    col("change_abs", "numeric", "Absolute one-day price change."),
                    col("change_pct", "numeric", "One-day percent change."),
                    col("volume", "numeric", "Shares traded during the session."),
                    col("turnover_cr", "numeric", "Turnover in crore rupees."),
                    col("total_trades", "numeric", "Number of trades when available."),
                    col("delivery_qty", "numeric", "Delivered quantity when available."),
                    col("delivery_pct", "numeric", "Delivery percentage when available."),
                    col("week52_high", "numeric", "52-week high from source data."),
                    col("week52_low", "numeric", "52-week low from source data."),
                    col("market_cap_cr", "numeric", "Market capitalization in crore rupees when available."),
                ),
                primary_key=("trade_date", "symbol"),
                latest_date_column="trade_date",
                common_filters=("series = 'EQ' for ordinary cash-equity stock analysis when series is required.",),
            ),
            "market.index_eod": TableSchema(
                name="market.index_eod",
                description="Indian index EOD OHLCV, trend, RSI, momentum, and signal fields.",
                columns=(
                    "trade_date",
                    "index_symbol",
                    "open",
                    "high",
                    "low",
                    "close",
                    "prev_close",
                    "change_pct",
                    "volume",
                    "turnover_cr",
                    "total_trades",
                    "week52_high",
                    "week52_low",
                    "technical_score",
                    "rsi",
                    "momentum_50d",
                    "relative_strength",
                    "trend_signal",
                    "trading_signal",
                ),
                column_details=(
                    col("trade_date", "date", "EOD trading date for the index bar."),
                    col("index_symbol", "text", "Index name/symbol, for example Nifty 50 or Nifty Bank."),
                    col("open", "numeric", "Index open level."),
                    col("high", "numeric", "Index high level."),
                    col("low", "numeric", "Index low level."),
                    col("close", "numeric", "Index close level; use for multi-period returns."),
                    col("prev_close", "numeric", "Previous index close level."),
                    col("change_pct", "numeric", "One-day percent change."),
                    col("volume", "numeric", "Index volume when source provides it."),
                    col("turnover_cr", "numeric", "Index turnover in crore rupees when available."),
                    col("total_trades", "numeric", "Total trades when available."),
                    col("week52_high", "numeric", "52-week high level."),
                    col("week52_low", "numeric", "52-week low level."),
                    col("technical_score", "numeric", "Index technical score when computed."),
                    col("rsi", "numeric", "RSI value when computed."),
                    col("momentum_50d", "numeric", "50-day momentum when computed."),
                    col("relative_strength", "numeric", "Relative strength score/value when computed."),
                    col("trend_signal", "text", "Trend state label when computed."),
                    col("trading_signal", "text", "Trading signal label when computed."),
                ),
                primary_key=("trade_date", "index_symbol"),
                latest_date_column="trade_date",
            ),
            "scores.stage_snapshots": TableSchema(
                name="scores.stage_snapshots",
                description="Point-in-time Weinstein stage, technical, fundamental, and composite scores.",
                columns=(
                    "snapshot_date",
                    "symbol",
                    "company_name",
                    "sector",
                    "market_cap_cat",
                    "price",
                    "live_price",
                    "price_date",
                    "change_1d_pct",
                    "change_1w_pct",
                    "change_1m_pct",
                    "stage",
                    "stage_score",
                    "technical_score",
                    "rsi",
                    "trend_signal",
                    "trading_signal",
                    "relative_strength",
                    "supertrend_state",
                    "supertrend_value",
                    "can_slim_score",
                    "minervini_score",
                    "fundamental_score",
                    "enhanced_fund_score",
                    "earnings_quality",
                    "sales_growth",
                    "financial_strength",
                    "institutional_backing",
                    "investment_score",
                    "stance",
                    "narrative",
                    "fund_details",
                    "source_csv",
                ),
                column_details=(
                    col("snapshot_date", "date", "Date for the point-in-time stage snapshot."),
                    col("symbol", "text", "Canonical NSE symbol."),
                    col("company_name", "text", "Company display name when available."),
                    col("sector", "text", "Agent Adda normalized sector bucket."),
                    col("market_cap_cat", "text", "Market-cap category label when available."),
                    col("price", "numeric", "Snapshot close or latest price used for scores."),
                    col("live_price", "numeric", "Intraday/live price when available; may be null for EOD-only runs."),
                    col("price_date", "date", "Date associated with the price field."),
                    col("change_1d_pct", "numeric", "One-session percent change."),
                    col("change_1w_pct", "numeric", "Approximate one-week percent change."),
                    col("change_1m_pct", "numeric", "Approximate one-month percent change."),
                    col("stage", "text", "Weinstein stage label.", "STAGE_1", "STAGE_2", "STAGE_3", "STAGE_4", "UNKNOWN"),
                    col("stage_score", "numeric", "Normalized stage confidence/score."),
                    col("technical_score", "numeric", "Composite technical score."),
                    col("rsi", "numeric", "RSI value."),
                    col("trend_signal", "text", "Trend state label such as BULLISH or BEARISH."),
                    col("trading_signal", "text", "Signal label.", "STRONG_BUY", "BUY", "HOLD", "WEAK_HOLD", "SELL"),
                    col("relative_strength", "numeric", "Relative strength versus benchmark universe/index."),
                    col("supertrend_state", "text", "Supertrend state label."),
                    col("supertrend_value", "numeric", "Supertrend reference value."),
                    col("can_slim_score", "numeric", "CANSLIM-inspired score."),
                    col("minervini_score", "numeric", "Minervini-inspired score."),
                    col("fundamental_score", "numeric", "Legacy fundamental score."),
                    col("enhanced_fund_score", "numeric", "Enhanced fundamental score."),
                    col("earnings_quality", "numeric", "Earnings-quality subscore."),
                    col("sales_growth", "numeric", "Sales-growth subscore."),
                    col("financial_strength", "numeric", "Financial-strength subscore."),
                    col("institutional_backing", "numeric", "Institutional-backing subscore."),
                    col("investment_score", "numeric", "Composite investment score."),
                    col("stance", "text", "Narrative stance label when generated."),
                    col("narrative", "text", "Generated narrative text when present."),
                    col("fund_details", "jsonb", "Structured fundamental detail payload when present."),
                    col("source_csv", "text", "Source report/csv marker."),
                ),
                primary_key=("snapshot_date", "symbol"),
                latest_date_column="snapshot_date",
                common_filters=(
                    "Use snapshot_date = (SELECT MAX(snapshot_date) FROM scores.stage_snapshots) for latest stage data.",
                    "Use stage = 'STAGE_2' for Stage 2 filters; never use stage = 2.",
                    "Use trading_signal IN ('BUY', 'STRONG_BUY') for constructive buy-signal filters.",
                ),
                value_rules=(
                    "stage values are text labels: STAGE_1, STAGE_2, STAGE_3, STAGE_4, UNKNOWN.",
                    "trading_signal values are text labels such as STRONG_BUY, BUY, HOLD, WEAK_HOLD, SELL.",
                ),
            ),
            "scores.stage2_vcp_picks": TableSchema(
                name="scores.stage2_vcp_picks",
                description="Materialized Stage 2 VCP picks built from stage snapshots and EOD history.",
                columns=(
                    "snapshot_date",
                    "rank",
                    "symbol",
                    "company_name",
                    "sector",
                    "price",
                    "live_price",
                    "price_date",
                    "change_1d_pct",
                    "change_1w_pct",
                    "rsi",
                    "relative_strength",
                    "trading_signal",
                    "trend_signal",
                    "supertrend_state",
                    "investment_score",
                    "enhanced_fund_score",
                    "earnings_quality",
                    "sales_growth",
                    "financial_strength",
                    "vcp_score",
                    "vcp_breakout_pct",
                    "vcp_contraction_pct",
                    "stance",
                    "narrative",
                    "fund_details",
                    "source_report",
                    "created_at",
                    "updated_at",
                ),
                column_details=(
                    col("snapshot_date", "date", "Date for the materialized VCP pick row."),
                    col("rank", "integer", "Rank within the materialized pick set."),
                    col("symbol", "text", "Canonical NSE symbol."),
                    col("company_name", "text", "Company display name when available."),
                    col("sector", "text", "Agent Adda normalized sector bucket."),
                    col("price", "numeric", "Snapshot price."),
                    col("live_price", "numeric", "Intraday/live price when available."),
                    col("price_date", "date", "Date associated with price."),
                    col("change_1d_pct", "numeric", "One-session percent change."),
                    col("change_1w_pct", "numeric", "Approximate one-week percent change."),
                    col("rsi", "numeric", "RSI value."),
                    col("relative_strength", "numeric", "Relative strength value."),
                    col("trading_signal", "text", "Signal label.", "STRONG_BUY", "BUY", "HOLD", "WEAK_HOLD", "SELL"),
                    col("trend_signal", "text", "Trend state label."),
                    col("supertrend_state", "text", "Supertrend state label."),
                    col("investment_score", "numeric", "Composite investment score."),
                    col("enhanced_fund_score", "numeric", "Enhanced fundamental score."),
                    col("earnings_quality", "numeric", "Earnings-quality subscore."),
                    col("sales_growth", "numeric", "Sales-growth subscore."),
                    col("financial_strength", "numeric", "Financial-strength subscore."),
                    col("vcp_score", "numeric", "VCP quality score."),
                    col("vcp_breakout_pct", "numeric", "Distance from breakout/reference level in percent."),
                    col("vcp_contraction_pct", "numeric", "Contraction metric used by VCP scoring."),
                    col("stance", "text", "Narrative stance label when generated."),
                    col("narrative", "text", "Generated narrative text when present."),
                    col("fund_details", "jsonb", "Structured fundamental detail payload when present."),
                    col("source_report", "text", "Source report marker."),
                    col("created_at", "timestamp", "Materialization timestamp."),
                    col("updated_at", "timestamp", "Last update timestamp."),
                ),
                primary_key=("snapshot_date", "symbol"),
                latest_date_column="snapshot_date",
                common_filters=(
                    "Use snapshot_date = (SELECT MAX(snapshot_date) FROM scores.stage2_vcp_picks) for latest VCP picks.",
                    "Order by vcp_score DESC, rank ASC for top VCP candidates.",
                ),
            ),
            "portfolio.holdings": TableSchema(
                name="portfolio.holdings",
                description="Current portfolio holdings loaded by migration from data/holdings.csv.",
                columns=("symbol", "qty", "avg_cost", "buy_date"),
                column_details=(
                    col("symbol", "text", "Canonical NSE symbol for the holding."),
                    col("qty", "numeric", "Quantity held."),
                    col("avg_cost", "numeric", "Average acquisition cost."),
                    col("buy_date", "date", "Initial/representative buy date when available."),
                ),
                primary_key=("symbol",),
            ),
            "report.enhanced_runs": TableSchema(
                name="report.enhanced_runs",
                description="Generated enhanced report run metadata.",
                columns=(
                    "run_id",
                    "run_ts",
                    "analysis_date",
                    "universe_size",
                    "stocks_analyzed",
                    "stocks_filtered",
                    "indices_analyzed",
                    "market_composite_score",
                    "market_sentiment",
                    "notes",
                ),
                column_details=(
                    col("run_id", "text", "Enhanced report run identifier."),
                    col("run_ts", "timestamp", "Report generation timestamp."),
                    col("analysis_date", "date", "Market analysis date covered by the report."),
                    col("universe_size", "integer", "Universe size before filtering."),
                    col("stocks_analyzed", "integer", "Number of stocks analyzed."),
                    col("stocks_filtered", "integer", "Number of stocks retained after filters."),
                    col("indices_analyzed", "integer", "Number of indices analyzed."),
                    col("market_composite_score", "numeric", "Market composite score."),
                    col("market_sentiment", "text", "Market sentiment label."),
                    col("notes", "text", "Report notes."),
                ),
                primary_key=("run_id",),
                latest_date_column="run_ts",
            ),
            "report.enhanced_filtered_stocks": TableSchema(
                name="report.enhanced_filtered_stocks",
                description="Filtered stock rows for enhanced reports.",
                columns=(
                    "run_id",
                    "rank",
                    "symbol",
                    "score",
                    "recommendation",
                    "current_price",
                    "open_price",
                    "high_price",
                    "low_price",
                    "volume",
                    "trading_value_cr",
                    "weekly_signal",
                    "daily_signal",
                    "day_change_pct",
                    "rsi",
                    "above_50dma",
                    "above_200dma",
                    "tech_score",
                    "fund_score",
                    "rs_score",
                    "macd_signal",
                    "week52_position",
                    "volume_ratio",
                    "rs_vs_nifty500",
                ),
                column_details=(
                    col("run_id", "text", "Enhanced report run identifier; joins report.enhanced_runs.run_id."),
                    col("rank", "integer", "Rank within the report output."),
                    col("symbol", "text", "Canonical NSE symbol."),
                    col("score", "numeric", "Report score."),
                    col("recommendation", "text", "Report recommendation label."),
                    col("current_price", "numeric", "Current/report price."),
                    col("open_price", "numeric", "Open price."),
                    col("high_price", "numeric", "High price."),
                    col("low_price", "numeric", "Low price."),
                    col("volume", "numeric", "Volume."),
                    col("trading_value_cr", "numeric", "Trading value in crore rupees."),
                    col("weekly_signal", "text", "Weekly signal label."),
                    col("daily_signal", "text", "Daily signal label."),
                    col("day_change_pct", "numeric", "One-day percent change."),
                    col("rsi", "numeric", "RSI value."),
                    col("above_50dma", "boolean", "Whether price is above 50DMA."),
                    col("above_200dma", "boolean", "Whether price is above 200DMA."),
                    col("tech_score", "numeric", "Technical score."),
                    col("fund_score", "numeric", "Fundamental score."),
                    col("rs_score", "numeric", "Relative strength score."),
                    col("macd_signal", "text", "MACD signal label."),
                    col("week52_position", "numeric", "Position versus 52-week range."),
                    col("volume_ratio", "numeric", "Volume versus average volume."),
                    col("rs_vs_nifty500", "numeric", "Relative strength versus Nifty 500."),
                ),
                primary_key=("run_id", "symbol"),
            ),
            "scores.quarterly_results": TableSchema(
                name="scores.quarterly_results",
                description="Structured quarterly profit and loss rows loaded from company filings and Screener.",
                columns=(
                    "symbol",
                    "period_label",
                    "period_end",
                    "period_type",
                    "revenue",
                    "expenses",
                    "operating_profit",
                    "opm_pct",
                    "other_income",
                    "interest",
                    "depreciation",
                    "pbt",
                    "tax_pct",
                    "pat",
                    "eps",
                    "source",
                    "source_url",
                    "raw_json",
                    "fetched_at",
                ),
                primary_key=("symbol", "period_label"),
                latest_date_column="period_end",
                common_filters=(
                    "Use DISTINCT ON (symbol) ORDER BY symbol, period_end DESC NULLS LAST, fetched_at DESC for latest quarter per symbol.",
                    "Use period_type = 'quarter' for quarterly analysis when period_type is required.",
                ),
            ),
            "scores.annual_results": TableSchema(
                name="scores.annual_results",
                description="Structured annual profit and loss rows loaded from company filings and Screener.",
                columns=(
                    "symbol",
                    "period_label",
                    "period_end",
                    "period_type",
                    "revenue",
                    "expenses",
                    "operating_profit",
                    "opm_pct",
                    "other_income",
                    "interest",
                    "depreciation",
                    "pbt",
                    "tax_pct",
                    "pat",
                    "eps",
                    "dividend_payout_pct",
                    "source",
                    "source_url",
                    "raw_json",
                    "fetched_at",
                ),
                primary_key=("symbol", "period_label"),
                latest_date_column="period_end",
                common_filters=(
                    "Use DISTINCT ON (symbol) ORDER BY symbol, period_end DESC NULLS LAST, fetched_at DESC for latest annual row per symbol.",
                    "Use period_type = 'annual' for annual analysis when period_type is required.",
                ),
            ),
            "scores.balance_sheet": TableSchema(
                name="scores.balance_sheet",
                description="Structured annual balance sheet rows loaded from company filings and Screener.",
                columns=(
                    "symbol",
                    "period_label",
                    "period_end",
                    "period_type",
                    "equity_capital",
                    "reserves",
                    "borrowings",
                    "other_liabilities",
                    "total_liabilities",
                    "fixed_assets",
                    "cwip",
                    "investments",
                    "other_assets",
                    "total_assets",
                    "net_debt",
                    "source",
                    "source_url",
                    "raw_json",
                    "fetched_at",
                ),
                primary_key=("symbol", "period_label"),
                latest_date_column="period_end",
                common_filters=("Align balance-sheet rows to annual_results by symbol plus period_label or period_end when possible.",),
            ),
            "scores.cash_flow": TableSchema(
                name="scores.cash_flow",
                description="Structured annual cash-flow rows loaded from company filings and Screener.",
                columns=(
                    "symbol",
                    "period_label",
                    "period_end",
                    "period_type",
                    "operating_cf",
                    "investing_cf",
                    "financing_cf",
                    "net_cf",
                    "source",
                    "source_url",
                    "raw_json",
                    "fetched_at",
                ),
                primary_key=("symbol", "period_label"),
                latest_date_column="period_end",
                common_filters=("Align cash-flow rows to annual_results by symbol plus period_label or period_end when possible.",),
            ),
            "scores.results_analysis": TableSchema(
                name="scores.results_analysis",
                description="LLM-authored daily results analysis with growth, margin, narrative, and source-trail fields.",
                columns=(
                    "symbol",
                    "period_end",
                    "period_label",
                    "company_name",
                    "industry",
                    "filing_date",
                    "filing_url",
                    "audited",
                    "consolidated",
                    "business_summary",
                    "growth_yoy_revenue_pct",
                    "growth_qoq_revenue_pct",
                    "growth_yoy_pat_pct",
                    "growth_qoq_pat_pct",
                    "opm_delta_pp",
                    "eps_yoy_pct",
                    "pl_commentary",
                    "bs_commentary",
                    "cf_commentary",
                    "ratios_snapshot",
                    "credit_rating_note",
                    "credit_rating_source",
                    "fii_dii_context",
                    "insider_activity_note",
                    "key_strengths",
                    "key_risks",
                    "verdict",
                    "score",
                    "report_path",
                    "llm_model",
                    "source_trail",
                    "analysis_json",
                    "created_at",
                    "updated_at",
                ),
                primary_key=("symbol", "period_end"),
                latest_date_column="period_end",
                common_filters=(
                    "Use DISTINCT ON (symbol) ORDER BY symbol, period_end DESC NULLS LAST, updated_at DESC for latest analyzed result per symbol.",
                    "verdict values are beat, inline, miss, mixed, or unknown.",
                ),
            ),
            "signals.signal_log": TableSchema(
                name="signals.signal_log",
                description="Generated trading signals with entries, stops, targets, context, and outcome tracking.",
                columns=(
                    "id",
                    "date_issued",
                    "symbol",
                    "sector",
                    "company",
                    "signal",
                    "setup_class",
                    "investment_score",
                    "technical_score",
                    "rsi",
                    "supertrend_state",
                    "price_at_issue",
                    "entry_low",
                    "entry_high",
                    "stop_loss",
                    "target_1",
                    "target_2",
                    "regime_at_issue",
                    "fno_pcr",
                    "fno_oi_change_5d",
                    "fno_buildup",
                    "fno_signal",
                    "fii_flow_signal",
                    "insider_alert",
                    "insider_score",
                    "insider_detail",
                    "date_resolved",
                    "price_at_resolution",
                    "return_pct",
                    "hit_target",
                    "hit_stop",
                    "action_bucket",
                    "action_reason",
                ),
                primary_key=("date_issued", "symbol"),
                latest_date_column="date_issued",
            ),
            "signals.fii_dii_flows": TableSchema(
                name="signals.fii_dii_flows",
                description="Daily FII/DII cash-flow aggregates and flow trend labels.",
                columns=(
                    "trade_date",
                    "fii_net_today",
                    "dii_net_today",
                    "fii_net_5d",
                    "dii_net_5d",
                    "flow_signal",
                    "fii_trend",
                    "dii_trend",
                    "days_in_window",
                    "updated_at",
                ),
                primary_key=("trade_date",),
                latest_date_column="trade_date",
            ),
            "signals.regime_history": TableSchema(
                name="signals.regime_history",
                description="Market regime history with confidence and days in regime.",
                columns=("trade_date", "regime", "confidence", "days_in_regime", "updated_at"),
                primary_key=("trade_date",),
                latest_date_column="trade_date",
                value_rules=("regime values include BULL, BEAR, CHOP, and RECOVERY.",),
            ),
            "signals.bulk_block_deals": TableSchema(
                name="signals.bulk_block_deals",
                description="Bulk and block deal rows from exchange disclosures.",
                columns=(
                    "id",
                    "deal_date",
                    "symbol",
                    "security_name",
                    "entity",
                    "side",
                    "qty",
                    "price",
                    "deal_type",
                    "remarks",
                    "source",
                    "created_at",
                ),
                primary_key=("id",),
                latest_date_column="deal_date",
            ),
            "signals.corporate_events": TableSchema(
                name="signals.corporate_events",
                description="Corporate events such as results, dividends, splits, bonus issues, and AGMs.",
                columns=("id", "symbol", "event_type", "event_date", "purpose_raw", "detail", "source", "created_at"),
                primary_key=("id",),
                latest_date_column="event_date",
                value_rules=("event_type values include RESULTS, DIVIDEND, SPLIT, BONUS, and AGM.",),
            ),
            "signals.insider_alerts": TableSchema(
                name="signals.insider_alerts",
                description="Aggregated insider and institutional alert rows.",
                columns=(
                    "id",
                    "alert_date",
                    "symbol",
                    "alert_type",
                    "entity",
                    "qty",
                    "value_cr",
                    "category",
                    "detail",
                    "source",
                    "insider_score",
                    "created_at",
                ),
                primary_key=("id",),
                latest_date_column="alert_date",
            ),
            "breadth.market_daily": TableSchema(
                name="breadth.market_daily",
                description="Daily market breadth, TRIN, signal counts, sentiment, and Nifty 500 context.",
                columns=(
                    "trade_date",
                    "advances",
                    "declines",
                    "unchanged",
                    "adv_volume",
                    "dec_volume",
                    "net_ad",
                    "ad_oscillator",
                    "ad_summation",
                    "ad_signal",
                    "trin",
                    "trin_5d",
                    "trin_signal",
                    "trin_5d_signal",
                    "divergence",
                    "total_stocks",
                    "strong_buy_count",
                    "buy_count",
                    "hold_count",
                    "weak_hold_count",
                    "sell_count",
                    "bullish_pct",
                    "bearish_pct",
                    "avg_technical_score",
                    "market_sentiment",
                    "nifty500_close",
                    "generated_at",
                ),
                primary_key=("trade_date",),
                latest_date_column="trade_date",
            ),
            "breadth.sector_daily": TableSchema(
                name="breadth.sector_daily",
                description="Sector breadth snapshots with 50DMA participation, 5D change, and divergence labels.",
                columns=(
                    "snapshot_date",
                    "sector",
                    "index_name",
                    "pct_above_50dma",
                    "change_5d",
                    "breadth_signal",
                    "divergence_alert",
                ),
                primary_key=("snapshot_date", "sector"),
                latest_date_column="snapshot_date",
            ),
            "breadth.ma_pct_above": TableSchema(
                name="breadth.ma_pct_above",
                description="Daily percentage of stocks above moving averages and Stage 2 participation.",
                columns=(
                    "snapshot_date",
                    "pct_above_20dma",
                    "pct_above_50dma",
                    "pct_above_100dma",
                    "pct_above_200dma",
                    "stage2_pct",
                    "updated_at",
                ),
                primary_key=("snapshot_date",),
                latest_date_column="snapshot_date",
            ),
        },
        join_rules=(
            JoinRule(
                left_table="market.equity_eod",
                left_column="symbol",
                right_table="scores.stage_snapshots",
                right_column="symbol",
                condition="market.equity_eod.symbol = scores.stage_snapshots.symbol",
                notes=(
                    "Use this for stock price history plus latest stage/score context. "
                    "When aligning point-in-time rows, also align trade_date to snapshot_date or explicitly use latest rows from each table."
                ),
            ),
            JoinRule(
                left_table="market.equity_eod",
                left_column="trade_date",
                right_table="scores.stage_snapshots",
                right_column="snapshot_date",
                condition="market.equity_eod.trade_date = scores.stage_snapshots.snapshot_date",
                notes="Use only when exact same-date EOD/stage alignment is required.",
            ),
            JoinRule(
                left_table="scores.stage2_vcp_picks",
                left_column="symbol",
                right_table="scores.stage_snapshots",
                right_column="symbol",
                condition="scores.stage2_vcp_picks.symbol = scores.stage_snapshots.symbol",
                notes="Use with both tables filtered to their latest snapshot_date unless a historical comparison is requested.",
            ),
            JoinRule(
                left_table="portfolio.holdings",
                left_column="symbol",
                right_table="scores.stage_snapshots",
                right_column="symbol",
                condition="portfolio.holdings.symbol = scores.stage_snapshots.symbol",
                notes="Use for portfolio add/trim analysis with latest stage and score context.",
            ),
            JoinRule(
                left_table="portfolio.holdings",
                left_column="symbol",
                right_table="market.equity_eod",
                right_column="symbol",
                condition="portfolio.holdings.symbol = market.equity_eod.symbol",
                notes="Use for portfolio price history and P&L context; filter market.equity_eod to latest trade_date unless historical returns are requested.",
            ),
            JoinRule(
                left_table="report.enhanced_runs",
                left_column="run_id",
                right_table="report.enhanced_filtered_stocks",
                right_column="run_id",
                condition="report.enhanced_runs.run_id = report.enhanced_filtered_stocks.run_id",
                notes="Use for report QA and broken/missing enhanced-report stock data checks.",
            ),
            JoinRule(
                left_table="scores.quarterly_results",
                left_column="symbol",
                right_table="scores.stage_snapshots",
                right_column="symbol",
                condition="scores.quarterly_results.symbol = scores.stage_snapshots.symbol",
                notes="Use for latest-results analysis plus current stage/technical context.",
            ),
            JoinRule(
                left_table="scores.quarterly_results",
                left_column="symbol",
                right_table="scores.results_analysis",
                right_column="symbol",
                condition="scores.quarterly_results.symbol = scores.results_analysis.symbol",
                notes="Also align period_end when comparing structured filing facts to generated results narratives.",
            ),
            JoinRule(
                left_table="scores.quarterly_results",
                left_column="period_end",
                right_table="scores.results_analysis",
                right_column="period_end",
                condition="scores.quarterly_results.period_end = scores.results_analysis.period_end",
                notes="Use with symbol alignment for exact same-result-period comparisons.",
            ),
            JoinRule(
                left_table="scores.annual_results",
                left_column="symbol",
                right_table="scores.balance_sheet",
                right_column="symbol",
                condition="scores.annual_results.symbol = scores.balance_sheet.symbol",
                notes="Use symbol plus comparable period_end/period_label when calculating ROCE or balance-sheet-backed ratios.",
            ),
            JoinRule(
                left_table="scores.annual_results",
                left_column="symbol",
                right_table="scores.cash_flow",
                right_column="symbol",
                condition="scores.annual_results.symbol = scores.cash_flow.symbol",
                notes="Use symbol plus comparable period_end/period_label when reconciling PAT, EPS, and cash flow.",
            ),
            JoinRule(
                left_table="signals.fii_dii_flows",
                left_column="trade_date",
                right_table="signals.regime_history",
                right_column="trade_date",
                condition="signals.fii_dii_flows.trade_date = signals.regime_history.trade_date",
                notes="Use for same-day flow/regime context.",
            ),
            JoinRule(
                left_table="signals.fii_dii_flows",
                left_column="trade_date",
                right_table="breadth.market_daily",
                right_column="trade_date",
                condition="signals.fii_dii_flows.trade_date = breadth.market_daily.trade_date",
                notes="Use for same-day flow and market breadth confirmation.",
            ),
            JoinRule(
                left_table="signals.fii_dii_flows",
                left_column="trade_date",
                right_table="market.index_eod",
                right_column="trade_date",
                condition="signals.fii_dii_flows.trade_date = market.index_eod.trade_date",
                notes="Use for same-day institutional flow and index action; filter market.index_eod.index_symbol to the intended index.",
            ),
            JoinRule(
                left_table="signals.regime_history",
                left_column="trade_date",
                right_table="breadth.market_daily",
                right_column="trade_date",
                condition="signals.regime_history.trade_date = breadth.market_daily.trade_date",
                notes="Use for same-day regime and breadth diagnostics.",
            ),
            JoinRule(
                left_table="breadth.market_daily",
                left_column="trade_date",
                right_table="market.index_eod",
                right_column="trade_date",
                condition="breadth.market_daily.trade_date = market.index_eod.trade_date",
                notes="Use for same-day market breadth and index-level confirmation.",
            ),
            JoinRule(
                left_table="breadth.sector_daily",
                left_column="snapshot_date",
                right_table="breadth.ma_pct_above",
                right_column="snapshot_date",
                condition="breadth.sector_daily.snapshot_date = breadth.ma_pct_above.snapshot_date",
                notes="Use for same-day sector breadth and broad market moving-average participation.",
            ),
            JoinRule(
                left_table="breadth.sector_daily",
                left_column="sector",
                right_table="scores.stage_snapshots",
                right_column="sector",
                condition="breadth.sector_daily.sector = scores.stage_snapshots.sector",
                notes="Use with latest snapshot filters on both tables for sector leadership and stage participation screens.",
            ),
            JoinRule(
                left_table="signals.corporate_events",
                left_column="symbol",
                right_table="scores.stage_snapshots",
                right_column="symbol",
                condition="signals.corporate_events.symbol = scores.stage_snapshots.symbol",
                notes="Use for event-driven watchlists with current stage and technical context.",
            ),
            JoinRule(
                left_table="signals.corporate_events",
                left_column="symbol",
                right_table="scores.results_analysis",
                right_column="symbol",
                condition="signals.corporate_events.symbol = scores.results_analysis.symbol",
                notes="Use for result-event context; align event_date to filing_date or period_end only when the user asks for that date relationship.",
            ),
            JoinRule(
                left_table="signals.bulk_block_deals",
                left_column="symbol",
                right_table="scores.stage_snapshots",
                right_column="symbol",
                condition="signals.bulk_block_deals.symbol = scores.stage_snapshots.symbol",
                notes="Use for bulk/block deal watchlists with latest stage and score context.",
            ),
            JoinRule(
                left_table="signals.insider_alerts",
                left_column="symbol",
                right_table="scores.stage_snapshots",
                right_column="symbol",
                condition="signals.insider_alerts.symbol = scores.stage_snapshots.symbol",
                notes="Use for insider-alert watchlists with latest technical and fundamental context.",
            ),
            JoinRule(
                left_table="signals.signal_log",
                left_column="symbol",
                right_table="scores.stage_snapshots",
                right_column="symbol",
                condition="signals.signal_log.symbol = scores.stage_snapshots.symbol",
                notes="Use for signal outcome reviews with current stage/score context.",
            ),
            JoinRule(
                left_table="signals.signal_log",
                left_column="symbol",
                right_table="market.equity_eod",
                right_column="symbol",
                condition="signals.signal_log.symbol = market.equity_eod.symbol",
                notes="Use for signal outcome price history; constrain market.equity_eod trade_date to the issued/resolved window.",
            ),
        ),
        global_rules=(
            "Use PostgreSQL syntax, not SQLite syntax. Prefer CURRENT_DATE - INTERVAL '3 months' over date('now', '-3 months').",
            "For latest EOD rows, use trade_date = (SELECT MAX(trade_date) FROM market.equity_eod).",
            "For latest index rows, use trade_date = (SELECT MAX(trade_date) FROM market.index_eod).",
            "For latest stage snapshots, use snapshot_date = (SELECT MAX(snapshot_date) FROM scores.stage_snapshots).",
            "For latest VCP picks, use snapshot_date = (SELECT MAX(snapshot_date) FROM scores.stage2_vcp_picks).",
            "Stage values are text labels. Use stage = 'STAGE_2'; never use stage = 2 or stage = 'VCP'.",
            "Do not infer unavailable columns such as pivot_price, as_of_date, date, or avg_change unless they appear in approved_schema.tables.",
            "Prefer parameterized templates for user-provided dates, symbols, thresholds, and limits.",
            "Keep result sets bounded with LIMIT when producing candidate lists.",
        ),
    )
