"""Report rendering for Company + Sector X-Ray intelligence."""

from __future__ import annotations

import html
from datetime import datetime
from pathlib import Path


def render_company_xray_markdown(model: dict) -> str:
    symbol = model.get("symbol", "").upper()
    company_name = model.get("company_name", "")
    coverage = model.get("coverage", {})
    sections = model.get("sections", {})
    deliberation = model.get("deliberation", {})
    evidence = model.get("evidence", [])

    lines = [
        f"# Company X-Ray: {symbol}",
        "",
        f"**Company:** {company_name or symbol}",
        "**Mode:** Company-first, sector-expanded intelligence",
        "",
        "## Evidence Coverage",
        "",
        "| Area | Coverage |",
        "|---|---|",
    ]
    for key, value in coverage.items():
        if key == "known_gaps":
            continue
        lines.append(f"| {_title(key)} | {value} |")
    lines.extend(["", "### Known Gaps", ""])
    lines.extend(_bullet_list(coverage.get("known_gaps", [])))

    section_titles = [
        ("business_model", "Business Model"),
        ("customer_base", "Customer Base"),
        ("sector_structure", "Sector Structure"),
        ("market_share", "Market Share"),
        ("competitors", "Competitor Map"),
        ("rbi_impact", "RBI Monetary Policy Impact"),
        ("budget_impact", "Union Budget Impact"),
    ]
    for key, title in section_titles:
        lines.extend(["", f"## {title}", ""])
        lines.extend(_bullet_list(sections.get(key, [])))

    for key, title in [
        ("bull_case", "Bull Case"),
        ("bear_case", "Bear Case"),
        ("base_case", "Base Case"),
        ("open_questions", "Open Questions"),
    ]:
        lines.extend(["", f"## {title}", ""])
        lines.extend(_bullet_list(deliberation.get(key, [])))

    lines.extend(["", "## Evidence Table", "", "| Category | Tier | Date | Evidence |", "|---|---:|---|---|"])
    for row in evidence:
        lines.append(
            f"| {row.get('category', '')} | {row.get('source_tier', '')} | "
            f"{row.get('evidence_date', '')} | {str(row.get('text', '')).replace('|', '/')} |"
        )

    lines.extend(
        [
            "",
            "## Research-Only Disclaimer",
            "",
            "Not investment advice. For research and learning only. This report does not replace independent judgement, risk management, or regulatory obligations.",
            "",
        ]
    )
    return "\n".join(lines)


def render_company_xray_html(model: dict) -> str:
    markdown = render_company_xray_markdown(model)
    body = _markdown_to_basic_html(markdown)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape('Company X-Ray: ' + model.get('symbol', '').upper())}</title>
  <style>
    body {{ font: 15px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #172033; margin: 36px auto; max-width: 980px; padding: 0 24px; }}
    h1, h2, h3 {{ color: #0f172a; line-height: 1.2; }}
    h1 {{ font-size: 32px; border-bottom: 2px solid #d8e0ec; padding-bottom: 12px; }}
    h2 {{ margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 14px; }}
    table {{ border-collapse: collapse; width: 100%; margin: 12px 0 20px; }}
    th, td {{ border: 1px solid #d8e0ec; padding: 8px 10px; vertical-align: top; }}
    th {{ background: #f1f5f9; text-align: left; }}
    li {{ margin: 5px 0; }}
  </style>
</head>
<body>
{body}
<footer><p><small>Generated by Agent Adda Company X-Ray on {datetime.now().strftime('%Y-%m-%d %H:%M')}</small></p></footer>
</body>
</html>
"""


def write_company_xray_report(symbol: str, markdown: str, html_text: str, output_dir: Path) -> dict:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    clean_symbol = "".join(ch for ch in symbol.upper() if ch.isalnum() or ch in {"_", "-"})
    stem = f"company_xray_{clean_symbol}"
    md_path = out / f"{stem}.md"
    html_path = out / f"{stem}.html"
    md_path.write_text(markdown)
    html_path.write_text(html_text)
    return {"markdown": str(md_path), "html": str(html_path)}


def _bullet_list(items: list[str]) -> list[str]:
    if not items:
        return ["- Not available in this run."]
    return [f"- {item}" for item in items]


def _title(key: str) -> str:
    return key.replace("_", " ").title()


def _markdown_to_basic_html(markdown: str) -> str:
    output: list[str] = []
    in_table = False
    for line in markdown.splitlines():
        if line.startswith("|") and line.endswith("|"):
            cells = [html.escape(cell.strip()) for cell in line.strip("|").split("|")]
            if set(cells) == {"---"} or all(set(cell) <= {"-", ":"} for cell in cells):
                continue
            tag = "th" if not in_table else "td"
            if not in_table:
                output.append("<table>")
                in_table = True
            output.append("<tr>" + "".join(f"<{tag}>{cell}</{tag}>" for cell in cells) + "</tr>")
            continue
        if in_table:
            output.append("</table>")
            in_table = False
        if line.startswith("# "):
            output.append(f"<h1>{html.escape(line[2:])}</h1>")
        elif line.startswith("## "):
            output.append(f"<h2>{html.escape(line[3:])}</h2>")
        elif line.startswith("### "):
            output.append(f"<h3>{html.escape(line[4:])}</h3>")
        elif line.startswith("- "):
            output.append(f"<ul><li>{html.escape(line[2:])}</li></ul>")
        elif line.strip():
            output.append(f"<p>{html.escape(line)}</p>")
    if in_table:
        output.append("</table>")
    return "\n".join(output)
