#!/usr/bin/env python3
"""Build the Meera Industries report using the LT Foods report visual template."""
from __future__ import annotations

import html
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "reports/fundamental/ltfoods_2026-08-24.html"
OUTPUT = ROOT / "reports/fundamental/meera_2026-08-26_ltfoods.html"


def esc(value: str) -> str:
    return html.escape(value)


def link(url: str, label: str) -> str:
    return f'<a href="{esc(url)}" target="_blank" rel="noopener">{esc(label)}</a>'


def card(label: str, value: str, detail: str = "", colour: str = "") -> str:
    cls = f' class="metric-value {colour}"' if colour else ' class="metric-value"'
    return f'<div class="card"><span class="metric-label">{esc(label)}</span><strong{cls}>{esc(value)}</strong><span class="metric-detail">{esc(detail)}</span></div>'


def table(headers: list[str], rows: list[list[str]]) -> str:
    head = "".join(f"<th>{esc(x)}</th>" for x in headers)
    body = "".join("<tr>" + "".join(f"<td>{esc(x)}</td>" for x in row) + "</tr>" for row in rows)
    return f'<div class="table-wrap"><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


def section(title: str, note: str, body: str, ident: str = "") -> str:
    attr = f' id="{ident}"' if ident else ""
    return f'<section{attr}><div class="section-head"><h2>{esc(title)}</h2><p class="section-note">{esc(note)}</p></div>{body}</section>'


def build() -> str:
    reference = REFERENCE.read_text(encoding="utf-8")
    css = re.search(r"<style>(.*?)</style>", reference, re.S).group(1)

    sources = [
        link("https://www.screener.in/company/540519/", "Screener — Meera Industries"),
        link("https://meeraind.com/", "Meera Industries official website"),
        link("https://scanx.trade/stock-market-news/earnings/meera-industries-unveils-h1-fy26-results-diversification-into-cpp-films-and-global-expansion/25010814", "Scanx — H1 FY26 results"),
        link("https://scanx.trade/stock-market-news/orders-deals/meera-industries-limited-secures-2-03-crore-order-for-high-performance-filament-twister/33026536", "Scanx — ₹2.03 cr order"),
        link("https://tradebrains.in/meera-industries-bags-7-95-cr-textile-machinery-order-from-dnb-textiles/", "Trade Brains — ₹7.95 cr order"),
        link("https://hdfcsky.com/news/meera-industries-stock-gained-more-than-1-percent-today-as-company-got-new-order-of-135000", "HDFC Sky — USD 135,000 export orders"),
        link("https://www.business-standard.com/markets/capital-market-news/meera-industries-secures-domestic-order-of-rs-7-95-cr-126070200468_1.html", "Business Standard — domestic order"),
        link("https://www.indiantextilemagazine.in/meera-industries-relying-on-technology-to-reach-the-top/", "Indian Textile Magazine — company profile"),
    ]

    metrics = "".join([
        card("Company", "Meera Industries Ltd", "BSE SME 540519 | no NSE/F&O listing"),
        card("FY26 consolidated revenue", "₹37.83 cr", "Down from ₹40.17 cr in FY25", "red"),
        card("Q1 FY27 revenue", "₹12.35 cr", "Standalone; +30% YoY", "green"),
        card("Q1 FY27 PAT", "₹0.71 cr", "Standalone; +10% YoY", "green"),
        card("Promoter holding", "61.69%", "Dec 2025 to Mar 2026; no pledge reported"),
        card("Recent domestic order", "₹7.95 cr", "DNB Textiles; disclosed July 2026", "green"),
        card("Export footprint", "39 countries", "Six continents; US subsidiary"),
        card("CPP film capacity", "300 t/month", "New plastics division"),
    ])
    chart_src = "../latest/charts/MEERA_chart.html"
    financial_visual = '''<div class="card" style="margin-bottom:14px"><h3>Revenue vs Net Profit</h3><p>Standalone trend visual copied from Claude's Meera research artifact.</p><div style="display:flex;align-items:flex-end;gap:18px;height:100px;margin:14px 0 4px"><div style="display:flex;flex-direction:column;align-items:center;gap:5px"><div style="display:flex;align-items:flex-end;gap:3px;height:70px"><div style="width:28px;height:41px;background:var(--sky);border-radius:4px 4px 0 0"></div><div style="width:28px;height:11px;background:var(--green);border-radius:4px 4px 0 0"></div></div><small>FY24</small></div><div style="display:flex;flex-direction:column;align-items:center;gap:5px"><div style="display:flex;align-items:flex-end;gap:3px;height:70px"><div style="width:28px;height:58px;background:var(--sky);border-radius:4px 4px 0 0"></div><div style="width:28px;height:16px;background:var(--green);border-radius:4px 4px 0 0"></div></div><small>FY25</small></div><div style="display:flex;flex-direction:column;align-items:center;gap:5px"><div style="display:flex;align-items:flex-end;gap:3px;height:70px"><div style="width:28px;height:53px;background:var(--sky);border-radius:4px 4px 0 0"></div><div style="width:28px;height:4px;background:var(--red);border-radius:4px 4px 0 0"></div></div><small>FY26</small></div><div style="display:flex;flex-direction:column;align-items:center;gap:5px"><div style="display:flex;align-items:flex-end;gap:3px;height:70px"><div style="width:28px;height:20px;background:var(--sky);border-radius:4px 4px 0 0"></div><div style="width:28px;height:7px;background:var(--green);border-radius:4px 4px 0 0"></div></div><small>Q1 FY27</small></div><div style="font-size:11px;color:var(--muted);align-self:flex-end;padding-bottom:18px"><span style="color:var(--sky)">■ Revenue</span><br><span style="color:var(--green)">■ Net profit</span></div></div></div>'''

    claude_detail = '''<div class="grid cols-2">
<div class="card"><h3>Business model and products</h3><p>Meera is a listed Indian pure-play in specialty TFO twisting machinery for technical and carpet yarns. Product lines include TFO Twister-70/90, TPRS double-stage machines, filament twisters, spun-staple twisters, servo cop winders, BCF heat-setting machines, ring twisters, covering machines, and CPP film lines. The company is a niche capital-goods manufacturer rather than a broad textile-equipment conglomerate.</p></div>
<div class="card"><h3>Scale and market position</h3><p>Approximate market capitalisation was ₹75 crore. The company is on BSE SME, has thin liquidity, no analyst coverage, and no reported FII, DII, or mutual-fund ownership. The research describes Meera as one of the smallest publicly listed Indian textile-machinery makers.</p></div>
</div>
<div class="card" style="margin-top:14px"><h3>Full financial and segment detail</h3>''' + table(["Period", "Revenue", "Net profit", "Margin / change"], [
        ["FY24 standalone", "~₹35.0 cr", "~₹2.30 cr", "~6.6% margin"],
        ["FY25 standalone", "₹40.26 cr", "₹3.89 cr", "9.7%; revenue +15%, PAT +69%"],
        ["FY26 standalone", "₹36.75 cr", "₹0.85 cr", "2.3%; revenue -8.7%, PAT -78%"],
        ["FY26 consolidated", "₹37.83 cr", "₹0.98 cr", "2.6%; revenue -5.8%, PAT -74%"],
        ["Q1 FY27 standalone", "₹12.35 cr", "₹0.71 cr", "5.7%; revenue +30%, PAT +10% YoY"],
    ]) + '''<p><strong>Q1 FY27 segment breakdown:</strong> Machine Division revenue ₹861.40 lakh (+19% YoY), segment result ₹77.44 lakh, with margin compressed versus the prior year. Plastic/CPP Division revenue ₹373.20 lakh (+66%), segment result ₹16.09 lakh, versus a ₹42.66 lakh loss previously. Total Q1 expenses also rose 30%, so operating leverage had not yet materially appeared. Q4 FY26 moved to an operating loss.</p></div>
<div class="grid cols-3" style="margin-top:14px">
<div class="card"><h3>Balance sheet</h3><p>Total equity ₹28.20 cr; total debt ₹5.85 cr; debt/equity 0.21x; cash and equivalents ₹2.82 cr; interest coverage 45.3x. The FY25 audit was clean and unqualified.</p></div>
<div class="card"><h3>Cash flow</h3><p>FY25 free cash flow was approximately negative ₹3 cr, likely reflecting working-capital build and CPP capex. Cash conversion should be checked against FY27 filings.</p></div>
<div class="card"><h3>Capital actions</h3><p>A 1:2 share split was announced in March 2026; post-split face value is ₹5.</p></div>
</div>
<div class="card" style="margin-top:14px"><h3>Complete order and export record</h3>''' + table(["Timing", "Customer / market", "Order", "Status"], [
        ["Jul 2026", "DNB Textiles, Surat", "₹7.95 cr high-speed BSY yarn TFO twisting line plus cop winder", "Delivery Q2 FY27"],
        ["Feb 2026", "Indospun LLP", "₹2.03 cr heavy-duty tangential-belt filament twister for PP sewing thread", "Delivery Q1 FY27"],
        ["H2 FY26", "YarnTex Pty Ltd, South Africa", "USD 84,000 spun twister with heavy-duty tape-drive spindle", "Delivered"],
        ["H2 FY26", "Teras Adhi Karisma PT, Indonesia", "USD 51,000 TPRS twister with precision take-up", "Delivered"],
        ["Ongoing", "CPP Films customers", "Approx. ₹20 cr book for cast polypropylene flexible-packaging films", "Rolling"],
    ]) + '''<p>The DNB order is described as the largest disclosed recent domestic machinery order and provides near-term H2 FY27 visibility. Meera exports to 39 countries across six continents. Meera Industries USA LLC has operated from High Point, North Carolina since 2017; the location is relevant to furniture, carpet, and BCF yarn customers. Named markets include Germany, Spain, Thailand, Belgium, Turkey, Indonesia, South Africa, the USA, Canada, and South America. Export revenue share is not publicly disclosed.</p></div>
<div class="grid cols-2" style="margin-top:14px">
<div class="card"><h3>Management and ownership</h3><p>Dharmesh Vinodbhai Desai (DIN 00292502, approximately age 44) is Chairman, Managing Director, and CFO from February 2026. He holds a B.E. in Mechanical Engineering from NIT Surat / South Gujarat University, previously worked at Garden Silk Mills and Premier Looms, founded Meera in 2006, and took it public in 2017. He has 19+ years with the company and handles business development, international marketing, and capacity expansion. His wife Bijalben Desai holds 29.1%.</p><p>Promoters hold 61.69%: Dharmesh Desai 32.3% and Bijalben Desai 29.1%. Public holding is 38.3%. No promoter pledge was reported, promoter holding was stable from December 2025 to March 2026, and FII/DII/MF holding was zero.</p></div>
<div class="card"><h3>Governance snapshot</h3><p>FY25 statutory audit opinion was clean and unqualified. Internal financial controls were considered adequate, with a comment that they could be more effective. Related-party compliance under Sections 177 and 188 was disclosed; statutory dues were current, with no arrears over six months; and the auditor reported no loan defaults. No credit rating was published.</p><p>Internal auditor D D R &amp; Co resigned on 29 May 2026. Replacement status was not confirmed in the research. The 20th AGM was scheduled for 29 September 2026. The concurrent CMD/CFO role and the auditor resignation are the principal governance watch items.</p></div>
</div>
<div class="card" style="margin-top:14px"><h3>Competitive landscape</h3><p>Veejay Lakshmi Engineering Works of Coimbatore is described as the dominant domestic TFO player, with roughly 70% domestic share in some descriptions and 5,000+ machines globally. Other relevant names are Himson Engineering and Weavetech Engineers in Surat, Alconetex in Gujarat, Jaylaxmi, Allma/Saurer and SSM internationally, Giudici, and Lohia Corp in Kanpur. Meera’s differentiation is customisation for BSY, BCF carpet yarn, and PP sewing-thread applications, plus export relationships. Lohia is a larger company but has lower direct overlap because it focuses on HDPE/PP woven sacks and related machinery.</p></div>
<div class="card" style="margin-top:14px"><h3>Industry and structural tailwinds</h3>''' + table(["Theme", "Claude research data", "Interpretation"], [
        ["Global TFO market", "USD 2.2 bn to USD 3.8 bn by 2032", "6.2% CAGR; Asia-Pacific approximately 8%"],
        ["India technical textiles", "USD 17–21 bn in 2025", "Approximately 6% CAGR to 2035; MMF supports demand"],
        ["India carpet-yarn market", "USD 21.33 bn in 2025", "5.1% CAGR; BCF is a key growth segment"],
        ["Textiles PLI", "₹10,683 cr outlay FY26–30", "Indirect tailwind as downstream mills expand capacity"],
        ["Indian textile machinery", "Production -29%; exports -50% in FY25", "Recent sector-level headwind"],
        ["Indian textile exports", "+2.1% to ₹3.16 lakh cr in FY26", "Modest recovery, skewed toward MMF and technical textiles"],
    ]) + '''<p>Meera does not receive the PLI directly as a machinery OEM; the benefit is indirect through downstream yarn and fabric manufacturers purchasing equipment. The shift from cotton toward MMF and technical textiles is the structural demand thesis.</p></div>
<div class="card" style="margin-top:14px"><h3>Dividend history</h3>''' + table(["Ex-date", "Type", "Amount"], [["28 Nov 2025", "Interim", "₹0.50/share"], ["21 Feb 2025", "Interim", "₹0.50/share"], ["23 Aug 2024", "Interim", "₹0.50/share"], ["25 Feb 2022", "Interim", "₹0.50/share"], ["23 Sep 2021", "Final", "₹0.70/share"], ["19 Nov 2020", "Interim", "₹0.50/share"]]) + '''<p>Trailing yield was estimated at approximately 1.47% at ₹34, with payout around 25.5%. The research records 11 dividends since the 2017 IPO. FY26 final dividend had not been announced before the scheduled AGM.</p></div>
<div class="card" style="margin-top:14px"><h3>Complete risk register</h3><ul><li>CMD and CFO concentration since February 2026, with no disclosed CFO succession path.</li><li>Internal auditor resignation during an earnings-weak period; replacement unconfirmed.</li><li>CPP Films may dilute returns if the ₹20–25 cr revenue target and 300 t/month capacity do not mature.</li><li>Q1 FY27 revenue recovery did not yet produce clear operating leverage.</li><li>BSE SME liquidity and retail-only float create meaningful entry/exit risk.</li><li>No analyst coverage, consensus, or public brokerage price target.</li><li>Single-promoter dependency across technology, relationships, international marketing, and finance.</li><li>Negative FY25 FCF and possible working-capital stress after CPP capex.</li><li>Textile-machinery cyclicality; FY25 TMMA data showed a sharp sector contraction.</li></ul></div>
<div class="grid cols-2" style="margin-top:14px">
<div class="card"><h3>Bull case</h3><ul><li>Global TFO demand grows 6.2%, with Asia-Pacific at 8%.</li><li>DNB order supports near-term machine revenue.</li><li>CPP Films turned profitable in Q1 FY27.</li><li>39-country exports and a US subsidiary are unusual at this scale.</li><li>Zero promoter pledge, 45x interest coverage, and 0.21x D/E.</li><li>At roughly ₹75 cr market cap on ₹38 cr revenue, P/S was about 2x if margins recover.</li></ul></div>
<div class="card"><h3>Bear case and triggers</h3><ul><li>FY26 PAT fell 78%, with negative FCF and incomplete margin recovery.</li><li>Governance and auditor issues remain unresolved.</li><li>CPP Films has not yet proven its targeted scale.</li><li>Before adding exposure, check Q2 FY27 delivery/margins, the 29 Sep AGM, auditor replacement, CMD/CFO separation, CPP Films profitability, further export orders, and positive FY27 FCF.</li></ul></div>
</div>
<div class="callout" style="margin-top:14px"><strong>Claude research verdict: WATCHLIST — not a buy yet.</strong> The niche product, export depth, clean debt, and dividend history are constructive. FY26 weakness, governance flags, thin liquidity, and the unproven CPP-film ramp mean the case should be reassessed after Q2 FY27 and the AGM.</div>'''

    body = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agent Adda Research | Meera Industries (MEERA)</title><style>{css}</style></head><body><div class="page">
<header class="topbar"><div class="brand"><div class="mark">AA</div><span>AgentAdda Market Intelligence</span></div><nav class="nav" aria-label="Report sections"><a href="#fundamentals">Fundamentals</a><a href="#technicals">Technicals</a><a href="#competitive">Competition</a><a href="#risks">Risks</a></nav></header>
<section class="hero" style="border-top:0"><div><div class="eyebrow"><span class="dot"></span> Claude research converted to LT Foods report format</div><h1>Meera Industries Ltd <span>(MEERA)</span></h1><p class="subtitle">A specialised textile-machinery company with exposure to twisting, winding, heat-setting, technical yarns, and a new CPP films division. The research case is supported by order wins and export reach, but FY26 earnings were weak and the diversification must still prove durable returns.</p><p class="meta">Research refreshed 26 Aug 2026. Financial and operating figures are drawn from Claude’s source-backed research; verify against exchange filings before publication.</p></div><aside class="hero-panel"><div class="metric-label">Research stance</div><div class="price">Monitor</div><div class="move">Recovery evidence, but execution risk remains</div><div class="verdict"><strong>Decision frame:</strong> the order pipeline and Q1 FY27 recovery are constructive; the key tests are margin recovery, CPP-film profitability, cash conversion, and governance quality.</div><div class="badge-row"><span class="badge">BSE 540519</span><span class="badge">61.69% promoter</span><span class="badge">39 export countries</span><span class="badge">₹7.95 cr order</span></div></aside></section>
<section><div class="grid cols-4">{metrics}</div></section>
{section("Investment Read", "Separate the business opportunity from the proof still required.", '<div class="narrative"><div class="card"><p class="pullquote">The opportunity is real; the next proof point is whether orders and new capacity become repeatable cash earnings.</p><p>Meera operates in textile machinery, with products spanning TFO twisters, filament and spun-yarn machines, winding, cabling, and heat-setting equipment. Its technical-textile orientation and export presence provide differentiation, while the CPP films entry adds a second growth vector.</p><p>FY26 was a setback: consolidated revenue declined to ₹37.83 crore and standalone PAT fell to ₹0.85 crore. Q1 FY27 showed improvement, including a profitable plastics division according to the research collected by Claude. That recovery needs confirmation across several quarters.</p></div><div class="card"><h3>Decision Frame</h3><ul><li><strong>Business:</strong> specialised textile machinery plus CPP films.</li><li><strong>Growth:</strong> large disclosed orders and export reach.</li><li><strong>Financials:</strong> FY26 margin/profit compression.</li><li><strong>Governance:</strong> CMD additionally appointed CFO; auditor change requires monitoring.</li><li><strong>Action bias:</strong> evidence-led watchlist, not a completed conviction case.</li></ul></div></div>')}
{section("Fundamental Scores", "No Agent Adda score snapshot was available in the Claude research artifact; the evidence is presented directly instead.", '<div class="card"><div class="callout">Score bars are intentionally not fabricated. The current evidence base supports a qualitative recovery assessment, while a refreshed MEERA database snapshot is still required for technical and fundamental scoring.</div></div>', "fundamentals")}
{section("Company Overview", "Business and product context from the Claude research pack.", '<div class="grid cols-3"><div class="card"><h3>Business</h3><p>Meera manufactures twisting, cabling, winding, and continuous heat-setting machinery for textile and technical-yarn applications.</p></div><div class="card"><h3>Products</h3><p>TFO Twister-70/90, filament yarn twisters, spun staple yarn twisters, TPRS machines, cop winders, and BCF/carpet-yarn equipment.</p></div><div class="card"><h3>Expansion</h3><p>The CPP films division targets flexible packaging, with stated installed capacity of 300 tonnes per month.</p></div></div>')}
{section("Historical P&L", "FY26 contracted before the reported Q1 FY27 recovery.", financial_visual + table(["Metric", "FY25", "FY26", "Change"], [["Consolidated revenue", "₹40.17 cr", "₹37.83 cr", "-5.8%"],["Standalone revenue", "₹40.26 cr", "₹36.75 cr", "-8.7%"],["Standalone net profit", "₹3.89 cr", "₹0.85 cr", "-78%"],["Q4 FY26", "—", "₹0.64 cr net loss", "Weak quarter"]]))}
{section("Quarterly Results", "The available Q1 FY27 evidence points to early recovery, but the period base and standalone/consolidated distinction must be checked.", table(["Period", "Revenue", "PAT", "Read-through"], [["Q1 FY27", "₹12.35 cr standalone", "₹0.71 cr", "+30% revenue, +10% PAT YoY"],["Q4 FY26", "—", "₹0.64 cr loss", "Weak base year exit"],["H1 FY26 CPP films", "Order book ₹20 cr", "—", "Capacity 300 t/month"]]))}
{section("Balance Sheet And Cash Flow", "The Claude artifact did not provide a complete audited balance-sheet and cash-flow table.", '<div class="card"><p>Before upgrading conviction, reconcile borrowings, receivables, inventory, CPP-film capex, CFO versus PAT, and any working-capital funding against the annual report and latest exchange filing.</p></div>')}
{section("Growth Story", "Order conversion and new-segment execution are the main growth variables.", '<div class="grid cols-2"><div class="card"><h3>What Can Work</h3><ul><li>₹7.95 crore DNB Textiles order, the largest disclosed recent domestic order.</li><li>₹2.03 crore Indospun order for a heavy-duty filament twister.</li><li>Exports to 39 countries and a US subsidiary serving North America and Latin America.</li><li>CPP films division adds flexible-packaging exposure.</li></ul></div><div class="card"><h3>What Must Be Proven</h3><ul><li>Order book becomes revenue and cash on schedule.</li><li>CPP films reaches sustainable profitability without stressing the balance sheet.</li><li>FY26 margin compression reverses.</li><li>Export growth is supported by disclosed economics, not only machine shipments.</li></ul></div></div>')}
{section("Indian Market And Sector Context", "Meera sits at the intersection of textile machinery, technical textiles, and flexible packaging.", '<div class="grid cols-3"><div class="card"><span class="metric-label">Core market</span><strong class="metric-value">Technical textiles</strong><span class="metric-detail">Twisting, winding, carpet and industrial yarn applications</span></div><div class="card"><span class="metric-label">Diversification</span><strong class="metric-value">CPP films</strong><span class="metric-detail">Flexible packaging; 300 t/month installed capacity</span></div><div class="card"><span class="metric-label">Tailwind</span><strong class="metric-value green">Export + PLI</strong><span class="metric-detail">Technical textiles and downstream capex</span></div></div>')}
{section("Competitive Landscape", "The competitive set is broader than a single listed peer.", table(["Company", "Positioning", "Implication for Meera"], [["Veejay Lakshmi", "Largest Indian TFO manufacturer; 70%+ claims in some segments", "Scale and domestic breadth are a benchmark"],["Lohia Group", "Broader textile machinery and composites", "Larger diversified competitor"],["Himson Engineering", "Surat-based spinning/twisting machinery", "Regional direct competitor"],["Allma / Saurer", "Global technical-textile and tyre-cord systems", "Technology benchmark"],["Meera Industries", "Technical textiles, specialised twisting, exports", "Niche/export-led positioning"]]), "competitive")}
{section("Broker And Web View", "No dated broker target or formal analyst consensus was found in the Claude research pack.", '<div class="card"><p>The evidence available is primarily company disclosures, market-news coverage, product information, and order announcements. Treat third-party descriptions of market size or competitive position as context until reconciled with filings.</p></div>', "brokers")}
{section("Concall, Filings And News Perspective", "Key developments collected by Claude for follow-up verification.", '<div class="grid cols-3"><div class="card"><h3>Orders</h3><p>₹7.95 crore DNB Textiles order; ₹2.03 crore Indospun order; USD 135,000 Indonesia and South Africa export orders.</p></div><div class="card"><h3>Management</h3><p>CMD Dharmesh V Desai was additionally appointed CFO and KMP in February 2026. A 1:2 share split was also announced.</p></div><div class="card"><h3>Governance</h3><p>Promoter holding was reported at 61.69% with no pledge disclosure. Internal auditor D D R &amp; Co resigned in May 2026.</p></div></div>', "concall")}
{section("Agent Adda Chart", "BSE:540519 daily history with the standard Agent Adda indicator stack. Intraday and benchmark overlays depend on live data availability.", f'<div class="chart-frame"><iframe src="{chart_src}" title="MEERA TradingView-style chart"></iframe></div>', "chart")}
{section("Technical Analysis", "No verified Agent Adda technical snapshot was available in Claude’s research artifact.", '<div class="card"><p>Do not infer entry, stop, target, RSI, trend stage, or relative strength from this report. Refresh the market-data route for MEERA before adding technical conclusions.</p></div>', "technicals")}
{section("Weinstein And O'Neil Read", "Framework assessment is withheld until a verified price and volume history is available.", '<div class="card"><p>Use Stage, trend, breakout, volume, and relative-strength checks only after the MEERA symbol is resolved against the current exchange universe.</p></div>')}
{section("Multi Time Frame View", "A multi-timeframe view requires fresh daily, weekly, and monthly candles.", '<div class="card"><p>Pending verified technical data.</p></div>')}
{section("Valuation Scenarios", "No defensible valuation range was available from the Claude research artifact.", '<div class="card"><p>Build valuation only after reconciling FY26 and Q1 FY27 standalone/consolidated numbers, current market capitalisation, net debt, and sustainable earnings. Do not convert order value directly into equity value.</p></div>')}
{section("Issues And Risks", "The main risks are execution, financial recovery, governance, and evidence quality.", '<div class="grid cols-3"><div class="card risk-callout"><h3>Earnings Risk</h3><p>FY26 PAT fell sharply and Q4 was loss-making.</p></div><div class="card risk-callout"><h3>Execution Risk</h3><p>Large orders must convert into timely delivery, revenue, and cash.</p></div><div class="card risk-callout"><h3>Diversification Risk</h3><p>CPP films profitability and ramp-up remain to be proven.</p></div><div class="card risk-callout"><h3>Governance Risk</h3><p>CMD/CFO overlap and auditor resignation require filing-level review.</p></div><div class="card risk-callout"><h3>Liquidity Risk</h3><p>Small-company liquidity and limited institutional ownership can amplify volatility.</p></div><div class="card risk-callout"><h3>Evidence Risk</h3><p>Missing balance-sheet, cash-flow, valuation, and technical snapshot data limits conviction.</p></div></div>', "risks")}
{section("Actionable Watch Plan", "Research checkpoints before any publication or decision use.", table(["Checkpoint", "What confirms", "What weakens the case"], [["Q1–Q2 FY27", "Revenue and PAT recovery persists", "Another margin/profit setback"],["DNB / Indospun orders", "Delivery and cash collection on schedule", "Delays, cancellations, or receivable build"],["CPP films", "Sustained profitability and utilisation", "Losses or funding stress"],["Governance", "Clear role separation and auditor transition", "Qualification, related-party, or disclosure issues"],["Market data", "Resolved symbol and complete technical snapshot", "Unresolved ticker or stale prices"]]))}
{section("Additional Perspective", "Full company, financial, order, industry, governance, dividend, risk, and verdict detail captured from the Claude-generated research artifact.", claude_detail, "claude-research")}
{section("Evidence Trail", "Primary and secondary sources used in Claude’s research pack.", '<ol class="source-list">' + "".join(f"<li>{x}</li>" for x in sources) + '</ol>')}
<div class="footer"><strong>Research-only disclaimer:</strong> This Agent Adda report is for educational and research purposes only. It is not investment advice or a buy/sell/hold recommendation. Verify all figures against company filings, exchange disclosures, and current market data before acting.</div></div></body></html>'''
    OUTPUT.write_text(body, encoding="utf-8")
    print(OUTPUT)


if __name__ == "__main__":
    build()
