"""
Send the latest NSE Market Report via WhatsApp using Twilio.
Finds the most recently generated HTML report and sends a summary + public link.
"""
import os
import glob
import sys
from pathlib import Path
from datetime import datetime

from twilio.rest import Client


def get_latest_report() -> tuple[Path, str] | None:
    """Return (path, repo-relative-path) for the best available report."""
    root = Path(__file__).parent.parent

    # Prefer the full NSE market report
    nse_files = sorted(glob.glob(str(root / "reports" / "NSE_Market_Report_*.html")), reverse=True)
    if nse_files:
        p = Path(nse_files[0])
        return p, f"reports/{p.name}"

    # Fall back to the auto components HTML report generated by the pipeline
    fallback = root / "working-sector" / "output" / "auto_components_comprehensive_report.html"
    if fallback.exists():
        return fallback, "working-sector/output/auto_components_comprehensive_report.html"

    return None


def build_message(report_path: Path, report_url: str) -> str:
    date_str = datetime.utcnow().strftime("%d %b %Y")

    if "NSE_Market_Report" in report_path.name:
        body = (
            f"*Report covers:*\n"
            f"• NSE Universe (803 stocks) — BUY signals, index dashboard, top-ranked stocks\n"
            f"• Auto Components sector deep-dive — top 15 shortlist, backtest summary"
        )
    else:
        body = (
            f"*Report covers:*\n"
            f"• Auto Components sector deep-dive — top 15 shortlist, backtest summary, sector narrative"
        )

    return (
        f"*NSE Market Intelligence Report — {date_str}*\n\n"
        f"📊 Auto-generated after market close (NSE)\n\n"
        f"{body}\n\n"
        f"🔗 *View report:*\n{report_url}\n\n"
        f"_For research use only. Not investment advice._"
    )


def send_whatsapp(message: str) -> None:
    account_sid = os.environ["TWILIO_ACCOUNT_SID"]
    auth_token = os.environ["TWILIO_AUTH_TOKEN"]
    from_number = os.environ["TWILIO_FROM"]   # e.g. whatsapp:+14155238886
    to_number = os.environ["TWILIO_TO"]       # e.g. whatsapp:+919XXXXXXXXX

    client = Client(account_sid, auth_token)
    msg = client.messages.create(
        from_=from_number,
        to=to_number,
        body=message,
    )
    print(f"WhatsApp message sent. SID: {msg.sid}")


def main() -> None:
    result = get_latest_report()
    if not result:
        print("No report found — skipping WhatsApp notification.")
        sys.exit(0)

    report_path, repo_rel_path = result
    print(f"Sending report: {repo_rel_path}")

    repo = os.environ.get("GITHUB_REPOSITORY", "pradeggg/unified-nse-analysis")
    branch = os.environ.get("GITHUB_REF_NAME", "main")
    report_url = (
        f"https://htmlpreview.github.io/?"
        f"https://raw.githubusercontent.com/{repo}/{branch}/{repo_rel_path}"
    )

    message = build_message(report_path, report_url)
    send_whatsapp(message)


if __name__ == "__main__":
    main()
