"""Session export to HTML/PDF."""
from __future__ import annotations
import os, re, datetime, html as _html

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXPORT_DIR = os.path.join(ROOT, "data", "exports")


def _strip_ansi(text: str) -> str:
    return re.sub(r'\x1b\[[0-9;]*[mK]', '', text)


def _rich_markup_to_html(text: str) -> str:
    """Convert Rich markup tags to basic HTML styling."""
    text = _html.escape(text)
    # Bold
    text = re.sub(r'\[bold(?:\s+\w+)?\](.*?)\[/(?:bold\s*\w*|)\]', r'<strong>\1</strong>', text, flags=re.DOTALL)
    text = re.sub(r'\[bold\](.*?)\[/bold\]', r'<strong>\1</strong>', text, flags=re.DOTALL)
    # Colors
    text = re.sub(r'\[green\](.*?)\[/(?:green|)\]', r'<span style="color:#4ade80">\1</span>', text, flags=re.DOTALL)
    text = re.sub(r'\[red\](.*?)\[/(?:red|)\]', r'<span style="color:#f87171">\1</span>', text, flags=re.DOTALL)
    text = re.sub(r'\[yellow\](.*?)\[/(?:yellow|)\]', r'<span style="color:#fbbf24">\1</span>', text, flags=re.DOTALL)
    text = re.sub(r'\[cyan\](.*?)\[/(?:cyan|)\]', r'<span style="color:#22d3ee">\1</span>', text, flags=re.DOTALL)
    text = re.sub(r'\[dim\](.*?)\[/(?:dim|)\]', r'<span style="opacity:0.6">\1</span>', text, flags=re.DOTALL)
    # Strip remaining Rich tags
    text = re.sub(r'\[/?[a-zA-Z0-9_ #;:.]+\]', '', text)
    # Newlines to <br>
    text = text.replace('\n', '<br>')
    return text


HTML_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Agent Adda — {title}</title>
<style>
  :root {{
    --bg: #0f0f0f;
    --surface: #1a1a1a;
    --border: #2a2a2a;
    --text: #e5e5e5;
    --dim: #888;
    --accent: #22d3ee;
    --green: #4ade80;
    --red: #f87171;
    --yellow: #fbbf24;
    --user-bg: #1e293b;
    --ai-bg: #1a1a1a;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; font-size: 14px; line-height: 1.6; }}
  .header {{ background: var(--surface); border-bottom: 1px solid var(--border); padding: 20px 32px; display: flex; align-items: center; gap: 16px; }}
  .header h1 {{ font-size: 20px; color: var(--accent); font-weight: 700; }}
  .header .meta {{ color: var(--dim); font-size: 12px; }}
  .container {{ max-width: 960px; margin: 0 auto; padding: 24px 16px; }}
  .message {{ margin-bottom: 16px; border-radius: 8px; overflow: hidden; border: 1px solid var(--border); }}
  .message-header {{ padding: 8px 16px; font-size: 11px; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase; }}
  .message-body {{ padding: 12px 16px; white-space: pre-wrap; font-family: 'Cascadia Code', 'Fira Code', 'Consolas', monospace; font-size: 13px; line-height: 1.7; }}
  .user .message-header {{ background: #1e3a5f; color: #93c5fd; }}
  .user .message-body {{ background: var(--user-bg); }}
  .assistant .message-header {{ background: #1a3028; color: var(--green); }}
  .assistant .message-body {{ background: var(--ai-bg); }}
  .system .message-header {{ background: #2a1f00; color: var(--yellow); }}
  .system .message-body {{ background: #1a1500; }}
  .footer {{ text-align: center; padding: 32px; color: var(--dim); font-size: 12px; border-top: 1px solid var(--border); margin-top: 32px; }}
  .stats {{ display: flex; gap: 24px; padding: 16px 32px; background: var(--surface); border-bottom: 1px solid var(--border); }}
  .stat {{ display: flex; flex-direction: column; }}
  .stat-value {{ font-size: 20px; font-weight: 700; color: var(--accent); }}
  .stat-label {{ font-size: 11px; color: var(--dim); text-transform: uppercase; }}
</style>
</head>
<body>
<div class="header">
  <div>
    <h1>🤖 Agent Adda — Research Session</h1>
    <div class="meta">{subtitle}</div>
  </div>
</div>
<div class="stats">
  <div class="stat"><span class="stat-value">{n_turns}</span><span class="stat-label">Turns</span></div>
  <div class="stat"><span class="stat-value">{n_user}</span><span class="stat-label">Queries</span></div>
  <div class="stat"><span class="stat-value">{exported_at}</span><span class="stat-label">Exported</span></div>
</div>
<div class="container">
{messages_html}
</div>
<div class="footer">Generated by Agent Adda · NSE Market Research Terminal · {date}</div>
</body>
</html>'''


def export_session_html(messages: list[dict], symbol: str = "", label: str = "") -> str:
    """Export session messages to a styled HTML file. Returns the file path."""
    os.makedirs(EXPORT_DIR, exist_ok=True)

    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    fname = f"{symbol+'_' if symbol else ''}{ts}.html"
    fpath = os.path.join(EXPORT_DIR, fname)

    title = f"{symbol} Research" if symbol else "Market Research"
    subtitle = f"Session exported {datetime.datetime.now().strftime('%d %b %Y, %H:%M')} IST"
    if label:
        subtitle = f"{label} · {subtitle}"

    user_msgs = [m for m in messages if m.get("role") == "user"]

    msgs_html_parts = []
    for msg in messages:
        role = msg.get("role", "assistant")
        content = _strip_ansi(msg.get("content", ""))
        content_html = _rich_markup_to_html(content)
        role_label = {"user": "👤 You", "assistant": "🤖 Agent Adda", "system": "⚙️ System"}.get(role, role.title())
        msgs_html_parts.append(f'''<div class="message {role}">
  <div class="message-header">{role_label}</div>
  <div class="message-body">{content_html}</div>
</div>''')

    html = HTML_TEMPLATE.format(
        title=title,
        subtitle=subtitle,
        n_turns=len(messages),
        n_user=len(user_msgs),
        exported_at=datetime.datetime.now().strftime("%H:%M"),
        messages_html="\n".join(msgs_html_parts),
        date=datetime.datetime.now().strftime("%d %b %Y"),
    )

    with open(fpath, "w", encoding="utf-8") as f:
        f.write(html)

    return fpath


def export_session_pdf(messages: list[dict], symbol: str = "", label: str = "") -> str:
    """Convert session to PDF. Falls back to HTML if PDF libs unavailable."""
    html_path = export_session_html(messages, symbol, label)
    pdf_path = html_path.replace(".html", ".pdf")

    # Try weasyprint
    try:
        import weasyprint
        weasyprint.HTML(filename=html_path).write_pdf(pdf_path)
        return pdf_path
    except ImportError:
        pass

    # Try pdfkit (requires wkhtmltopdf system binary)
    try:
        import pdfkit
        pdfkit.from_file(html_path, pdf_path)
        return pdf_path
    except Exception:
        pass

    # Fallback: return HTML path
    return html_path
