#!/usr/bin/env python3
"""Agent Adda — Interactive Setup Wizard.

Runs after install.sh and:
  1. Generates / updates .env from .env.template by prompting for each value
     (existing values preserved; user can press Enter to keep them).
  2. Verifies PostgreSQL connectivity (creates DB + role if asked).
  3. Applies idempotent SQL migrations under postgres/.
  4. Asks whether to install background services (launchd on macOS,
     systemd on Linux) and writes the unit files in place.
  5. Runs a smoke test (doctor.py) and prints next-steps.

All steps are skippable / re-runnable. Safe to call any number of times.

Usage:
    python installer/setup_wizard.py                # full interactive wizard
    python installer/setup_wizard.py --non-interactive  # use defaults / .env values, no prompts
    python installer/setup_wizard.py --check-only       # only run health checks

Env-vars handled (categorised; all optional unless marked REQUIRED):

  POSTGRES               REQUIRED   PG_DSN  (format: dbname=… user=… host=…)
  LLM PROVIDER           OPTIONAL   OPENAI_API_KEY, OPENAI_MODEL,
                                    OLLAMA_HOST,  OLLAMA_MODEL
  WEB SEARCH             OPTIONAL   SERPAPI_API_KEY, BING_SEARCH_KEY
  ANTHROPIC NARRATIVES   OPTIONAL   ANTHROPIC_API_KEY
  EMAIL REPORTS          OPTIONAL   SMTP_HOST, SMTP_PORT, SMTP_USER,
                                    SMTP_PASSWORD, EMAIL_FROM
  CAPTURE DAEMON KNOBS   OPTIONAL   AGENT_ADDA_CAPTURE_INTERVAL_SEC (=60)
                                    AGENT_ADDA_CAPTURE_RETENTION_MIN (=120)
                                    AGENT_ADDA_CAPTURE_PRUNE_SEC     (=1800)
"""
from __future__ import annotations

import argparse
import os
import platform
import re
import shutil
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"
ENV_TEMPLATE_PATH = ROOT / "installer" / ".env.template"
PLIST_TEMPLATE_DIR = ROOT / "installer" / "launchd"
SYSTEMD_TEMPLATE_DIR = ROOT / "installer" / "systemd"

# ─────────────────────────────────────────────────────────────────────────────
# tiny ANSI helpers (no external dep)
# ─────────────────────────────────────────────────────────────────────────────
_TTY = sys.stdout.isatty()
def _c(code: str, s: str) -> str:
    return f"\033[{code}m{s}\033[0m" if _TTY else s
BOLD = lambda s: _c("1", s)
DIM  = lambda s: _c("2", s)
RED  = lambda s: _c("31", s)
GRN  = lambda s: _c("32", s)
YEL  = lambda s: _c("33", s)
CYN  = lambda s: _c("36", s)

def _step(title: str) -> None:
    print(f"\n{BOLD('── ' + title + ' ──')}")
def _ok(msg: str) -> None:    print(f"  {GRN('✓')} {msg}")
def _info(msg: str) -> None:  print(f"  {CYN('•')} {msg}")
def _warn(msg: str) -> None:  print(f"  {YEL('⚠')} {msg}")
def _err(msg: str) -> None:   print(f"  {RED('✗')} {msg}")


# ─────────────────────────────────────────────────────────────────────────────
# .env handling
# ─────────────────────────────────────────────────────────────────────────────
ENV_TEMPLATE_CONTENT = dedent(
    """\
    # ─────────────────────────────────────────────────────────────────────
    # Agent Adda — Environment Configuration
    # Generated by installer/setup_wizard.py — safe to hand-edit.
    # All keys are OPTIONAL except PG_DSN.
    # ─────────────────────────────────────────────────────────────────────

    # PostgreSQL connection string (REQUIRED).
    # Examples:
    #   dbname=nse_market user=nse_admin host=/tmp        (unix socket)
    #   dbname=nse_market user=nse_admin host=localhost password=secret port=5432
    PG_DSN=dbname=nse_market user=nse_admin host=/tmp

    # ── LLM backend ─────────────────────────────────────────────────────
    # Either OpenAI (cloud, paid) or Ollama (local, free). At least one needed
    # for `/intel`, full agent answers, and the heat-calendar commentary.
    OPENAI_API_KEY=
    OPENAI_MODEL=gpt-4o
    OLLAMA_HOST=http://localhost:11434
    OLLAMA_MODEL=granite4

    # ── Web search (catalysts, news) — all optional ─────────────────────
    SERPAPI_API_KEY=
    BING_SEARCH_KEY=

    # ── Anthropic Claude (sector-rotation narratives) — optional ────────
    ANTHROPIC_API_KEY=

    # ── Email reports — optional ────────────────────────────────────────
    SMTP_HOST=
    SMTP_PORT=587
    SMTP_USER=
    SMTP_PASSWORD=
    EMAIL_FROM=

    # ── Intraday capture daemon knobs — optional ────────────────────────
    AGENT_ADDA_CAPTURE_INTERVAL_SEC=60
    AGENT_ADDA_CAPTURE_RETENTION_MIN=120
    AGENT_ADDA_CAPTURE_PRUNE_SEC=1800

    # ── Misc ────────────────────────────────────────────────────────────
    LOG_LEVEL=INFO
    """
)

def _ensure_template() -> None:
    """Write installer/.env.template if it doesn't exist."""
    if not ENV_TEMPLATE_PATH.exists():
        ENV_TEMPLATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        ENV_TEMPLATE_PATH.write_text(ENV_TEMPLATE_CONTENT)
        _ok(f"Wrote default template: {ENV_TEMPLATE_PATH.relative_to(ROOT)}")

def _load_env_file(path: Path) -> dict[str, str]:
    """Parse KEY=VALUE pairs from a .env file (no shell expansion)."""
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, _, v = s.partition("=")
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out

def _save_env(path: Path, values: dict[str, str], template_text: str) -> None:
    """Re-emit the template, replacing each KEY= with the value from `values`.
    Comments and ordering are preserved."""
    out_lines: list[str] = []
    for line in template_text.splitlines():
        m = re.match(r"^([A-Z][A-Z0-9_]*)\s*=", line)
        if m and m.group(1) in values:
            out_lines.append(f"{m.group(1)}={values[m.group(1)]}")
        else:
            out_lines.append(line)
    path.write_text("\n".join(out_lines) + "\n")
    try:
        path.chmod(0o600)
    except OSError:
        pass


# ─────────────────────────────────────────────────────────────────────────────
# 1.  prompt-driven .env wizard
# ─────────────────────────────────────────────────────────────────────────────
def _prompt(label: str, current: str = "", *, secret: bool = False, default: str = "") -> str:
    """Prompt for a value. Empty input keeps `current` (or `default`)."""
    show = current or default
    suffix = f" [{DIM(show if not secret else '••••')}]" if show else ""
    raw = input(f"    {label}{suffix}: ").strip()
    return raw or current or default

def _wizard_env(non_interactive: bool) -> dict[str, str]:
    _step("Step A  ·  Configure .env")
    _ensure_template()
    template_text = ENV_TEMPLATE_PATH.read_text()
    existing = _load_env_file(ENV_PATH)

    if non_interactive:
        _info(".env left as-is (non-interactive mode)")
        return existing

    print(f"  {DIM('Press Enter to keep the existing value shown in brackets.')}")
    print(f"  {DIM('Leave blank to disable that integration.')}\n")

    values = dict(existing)

    # Required
    print(f"  {BOLD('PostgreSQL')}")
    values["PG_DSN"] = _prompt(
        "PG_DSN",
        existing.get("PG_DSN", "dbname=nse_market user=nse_admin host=/tmp"),
    )

    # LLM
    print(f"\n  {BOLD('LLM backend')}  {DIM('(at least one — both optional but agent has reduced features without)')}")
    values["OPENAI_API_KEY"] = _prompt("OPENAI_API_KEY", existing.get("OPENAI_API_KEY", ""), secret=True)
    values["OPENAI_MODEL"]   = _prompt("OPENAI_MODEL",   existing.get("OPENAI_MODEL", "gpt-4o"))
    values["OLLAMA_HOST"]    = _prompt("OLLAMA_HOST",    existing.get("OLLAMA_HOST", "http://localhost:11434"))
    values["OLLAMA_MODEL"]   = _prompt("OLLAMA_MODEL",   existing.get("OLLAMA_MODEL", "granite4"))

    print(f"\n  {BOLD('Optional integrations')}  {DIM('(press Enter to skip)')}")
    values["SERPAPI_API_KEY"]   = _prompt("SERPAPI_API_KEY (web search)",       existing.get("SERPAPI_API_KEY", ""), secret=True)
    values["ANTHROPIC_API_KEY"] = _prompt("ANTHROPIC_API_KEY (Claude narratives)", existing.get("ANTHROPIC_API_KEY", ""), secret=True)

    if _yes(f"\n  Configure {BOLD('email reports')}? (SMTP)", default=False):
        values["SMTP_HOST"]     = _prompt("SMTP_HOST",     existing.get("SMTP_HOST", ""))
        values["SMTP_PORT"]     = _prompt("SMTP_PORT",     existing.get("SMTP_PORT", "587"))
        values["SMTP_USER"]     = _prompt("SMTP_USER",     existing.get("SMTP_USER", ""))
        values["SMTP_PASSWORD"] = _prompt("SMTP_PASSWORD", existing.get("SMTP_PASSWORD", ""), secret=True)
        values["EMAIL_FROM"]    = _prompt("EMAIL_FROM",    existing.get("EMAIL_FROM", ""))

    _save_env(ENV_PATH, values, template_text)
    _ok(f"Wrote {ENV_PATH.relative_to(ROOT)} (chmod 600)")
    return values


# ─────────────────────────────────────────────────────────────────────────────
# 2.  PostgreSQL provisioning
# ─────────────────────────────────────────────────────────────────────────────
def _parse_dsn(dsn: str) -> dict[str, str]:
    parts = {}
    for tok in dsn.split():
        if "=" in tok:
            k, _, v = tok.partition("=")
            parts[k.strip()] = v.strip()
    return parts

def _wizard_postgres(values: dict[str, str], non_interactive: bool) -> bool:
    _step("Step B  ·  PostgreSQL")
    dsn = values.get("PG_DSN", "").strip()
    if not dsn:
        _err("PG_DSN is empty — skipping PG step")
        return False
    try:
        import psycopg2  # type: ignore
    except ImportError:
        _err("psycopg2 not installed — did install.sh complete?")
        return False

    parts = _parse_dsn(dsn)
    db   = parts.get("dbname", "nse_market")
    user = parts.get("user",   "nse_admin")

    # Try connection
    try:
        conn = psycopg2.connect(dsn, connect_timeout=5)
        conn.close()
        _ok(f"Connected to PostgreSQL: dbname={db} user={user}")
    except Exception as e:
        _warn(f"Cannot connect: {e}")
        if non_interactive or not _yes(f"  Try to {BOLD('create')} db '{db}' and role '{user}' via psql?", default=True):
            _err("Cannot proceed without DB. Re-run after fixing connectivity.")
            return False
        if not _create_db_and_role(db, user):
            return False
        try:
            psycopg2.connect(dsn, connect_timeout=5).close()
            _ok("Connected after provisioning.")
        except Exception as e2:
            _err(f"Still cannot connect: {e2}")
            return False

    # Apply migrations
    pg_dir = ROOT / "postgres"
    if not pg_dir.is_dir():
        _info("No postgres/ directory — skipping schema migrations")
        return True
    sql_files = sorted(pg_dir.glob("*.sql"))
    if not sql_files:
        _info("No .sql files under postgres/ — skipping migrations")
        return True
    _info(f"Applying {len(sql_files)} migration(s) from postgres/")
    conn = psycopg2.connect(dsn)
    conn.autocommit = True
    for f in sql_files:
        try:
            with conn.cursor() as cur:
                cur.execute(f.read_text())
            _ok(f"  applied {f.name}")
        except Exception as e:
            _warn(f"  {f.name} skipped/failed: {str(e).splitlines()[0]}")
    conn.close()
    return True

def _create_db_and_role(db: str, user: str) -> bool:
    """Use locally-running psql as superuser to create db+role idempotently."""
    if not shutil.which("psql"):
        _err("psql not on PATH; cannot auto-create DB")
        return False
    sql = (
        f"DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname='{user}') "
        f"THEN CREATE ROLE {user} LOGIN; END IF; END $$;\n"
        f"SELECT 'CREATE DATABASE {db} OWNER {user}' WHERE NOT EXISTS "
        f"(SELECT FROM pg_database WHERE datname='{db}')\\gexec\n"
    )
    try:
        proc = subprocess.run(
            ["psql", "-d", "postgres", "-v", "ON_ERROR_STOP=1", "-X"],
            input=sql, text=True, capture_output=True, timeout=20,
        )
        if proc.returncode != 0:
            _err(f"psql failed: {proc.stderr.strip()}")
            return False
        _ok(f"Provisioned db '{db}' and role '{user}'")
        return True
    except Exception as e:
        _err(f"psql call errored: {e}")
        return False


# ─────────────────────────────────────────────────────────────────────────────
# 3.  Background services (launchd / systemd)
# ─────────────────────────────────────────────────────────────────────────────
LAUNCHD_DAILY_REFRESH = """\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>com.agentadda.daily_refresh</string>
    <key>ProgramArguments</key>
    <array>
        <string>__VENV__/bin/python3</string>
        <string>__ROOT__/daily_refresh.py</string>
    </array>
    <key>WorkingDirectory</key><string>__ROOT__</string>
    <key>StartCalendarInterval</key>
    <array>
        <dict><key>Hour</key><integer>16</integer><key>Minute</key><integer>15</integer><key>Weekday</key><integer>1</integer></dict>
        <dict><key>Hour</key><integer>16</integer><key>Minute</key><integer>15</integer><key>Weekday</key><integer>2</integer></dict>
        <dict><key>Hour</key><integer>16</integer><key>Minute</key><integer>15</integer><key>Weekday</key><integer>3</integer></dict>
        <dict><key>Hour</key><integer>16</integer><key>Minute</key><integer>15</integer><key>Weekday</key><integer>4</integer></dict>
        <dict><key>Hour</key><integer>16</integer><key>Minute</key><integer>15</integer><key>Weekday</key><integer>5</integer></dict>
    </array>
    <key>StandardOutPath</key><string>/tmp/agentadda_daily_refresh.log</string>
    <key>StandardErrorPath</key><string>/tmp/agentadda_daily_refresh.err</string>
    <key>RunAtLoad</key><false/>
</dict>
</plist>
"""

LAUNCHD_INTRADAY_CAPTURE = """\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>com.agentadda.intraday_capture</string>
    <key>ProgramArguments</key>
    <array>
        <string>__VENV__/bin/python3</string>
        <string>-c</string>
        <string>from terminal.intraday_capture import start_background_capture, _capture_loop, _prune_loop; start_background_capture()
import time
while True: time.sleep(3600)</string>
    </array>
    <key>WorkingDirectory</key><string>__ROOT__</string>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><true/>
    <key>StandardOutPath</key><string>/tmp/agentadda_capture.log</string>
    <key>StandardErrorPath</key><string>/tmp/agentadda_capture.err</string>
</dict>
</plist>
"""

SYSTEMD_DAILY_REFRESH = """\
[Unit]
Description=Agent Adda — Daily NSE Data Refresh
After=network-online.target postgresql.service

[Service]
Type=oneshot
WorkingDirectory=__ROOT__
ExecStart=__VENV__/bin/python __ROOT__/daily_refresh.py
StandardOutput=append:/var/log/agentadda_daily_refresh.log
StandardError=append:/var/log/agentadda_daily_refresh.err

[Install]
WantedBy=multi-user.target
"""

SYSTEMD_INTRADAY_CAPTURE = """\
[Unit]
Description=Agent Adda — Intraday Quote-Tape Capture
After=network-online.target postgresql.service

[Service]
Type=simple
WorkingDirectory=__ROOT__
ExecStart=__VENV__/bin/python -c "from terminal.intraday_capture import start_background_capture; start_background_capture(); import time; \\nwhile True: time.sleep(3600)"
Restart=always
RestartSec=15
StandardOutput=append:/var/log/agentadda_capture.log
StandardError=append:/var/log/agentadda_capture.err

[Install]
WantedBy=multi-user.target
"""

def _wizard_services(non_interactive: bool) -> None:
    _step("Step C  ·  Background services (optional)")
    venv = ROOT / ".venv"
    if not venv.exists():
        _warn("No .venv — skipping service installation")
        return

    if non_interactive:
        _info("Skipping service install (non-interactive)")
        return
    if not _yes("  Install always-on background services (daily refresh + intraday capture)?", default=False):
        _info("Skipped — you can install later with: make -C installer services")
        return

    sysname = platform.system()
    PLIST_TEMPLATE_DIR.mkdir(parents=True, exist_ok=True)
    SYSTEMD_TEMPLATE_DIR.mkdir(parents=True, exist_ok=True)

    if sysname == "Darwin":
        units = {
            "com.agentadda.daily_refresh.plist":    LAUNCHD_DAILY_REFRESH,
            "com.agentadda.intraday_capture.plist": LAUNCHD_INTRADAY_CAPTURE,
        }
        target_dir = Path.home() / "Library" / "LaunchAgents"
        target_dir.mkdir(parents=True, exist_ok=True)
        for name, body in units.items():
            rendered = body.replace("__VENV__", str(venv)).replace("__ROOT__", str(ROOT))
            staged = PLIST_TEMPLATE_DIR / name
            staged.write_text(rendered)
            target = target_dir / name
            shutil.copy(staged, target)
            subprocess.run(["launchctl", "unload", str(target)], capture_output=True)
            r = subprocess.run(["launchctl", "load", str(target)], capture_output=True, text=True)
            if r.returncode == 0:
                _ok(f"Loaded {name}")
            else:
                _warn(f"launchctl load {name}: {r.stderr.strip()}")
    elif sysname == "Linux":
        units = {
            "agentadda-daily-refresh.service":    SYSTEMD_DAILY_REFRESH,
            "agentadda-intraday-capture.service": SYSTEMD_INTRADAY_CAPTURE,
        }
        for name, body in units.items():
            rendered = body.replace("__VENV__", str(venv)).replace("__ROOT__", str(ROOT))
            staged = SYSTEMD_TEMPLATE_DIR / name
            staged.write_text(rendered)
            _info(f"Wrote {staged.relative_to(ROOT)}")
        print(f"\n    {DIM('To enable, copy to /etc/systemd/system and run:')}")
        print(f"    {CYN(f'sudo cp {SYSTEMD_TEMPLATE_DIR}/*.service /etc/systemd/system/')}")
        print(f"    {CYN('sudo systemctl daemon-reload && sudo systemctl enable --now agentadda-intraday-capture.service')}")
    else:
        _warn(f"No service manager available for {sysname}")


# ─────────────────────────────────────────────────────────────────────────────
# 4.  Smoke test (delegate to doctor.py)
# ─────────────────────────────────────────────────────────────────────────────
def _wizard_doctor() -> int:
    _step("Step D  ·  Health check")
    doctor = ROOT / "installer" / "doctor.py"
    if not doctor.exists():
        _warn("doctor.py not found — skipping")
        return 0
    return subprocess.run([sys.executable, str(doctor)]).returncode


# ─────────────────────────────────────────────────────────────────────────────
# helpers
# ─────────────────────────────────────────────────────────────────────────────
def _yes(prompt: str, *, default: bool = True) -> bool:
    suffix = " [Y/n]" if default else " [y/N]"
    try:
        ans = input(prompt + suffix + " ").strip().lower()
    except EOFError:
        return default
    if not ans:
        return default
    return ans in ("y", "yes")


# ─────────────────────────────────────────────────────────────────────────────
# main
# ─────────────────────────────────────────────────────────────────────────────
def main() -> int:
    p = argparse.ArgumentParser(description="Agent Adda interactive setup wizard.")
    p.add_argument("--non-interactive", action="store_true", help="Use existing .env / defaults; no prompts.")
    p.add_argument("--check-only",      action="store_true", help="Run health checks only.")
    p.add_argument("--skip-system", action="store_true", help=argparse.SUPPRESS)
    p.add_argument("--skip-wizard", action="store_true", help=argparse.SUPPRESS)
    p.add_argument("--check",       action="store_true", help=argparse.SUPPRESS)
    args = p.parse_args()

    if args.check_only or args.check:
        return _wizard_doctor()

    values = _wizard_env(non_interactive=args.non_interactive)
    _wizard_postgres(values, non_interactive=args.non_interactive)
    _wizard_services(non_interactive=args.non_interactive)
    rc = _wizard_doctor()

    print(f"\n{BOLD(GRN('Wizard complete.'))}\n")
    print(f"  Run the agent:    {CYN('.venv/bin/python nse_agent.py')}")
    print(f"  Re-run wizard:    {CYN('.venv/bin/python installer/setup_wizard.py')}")
    print(f"  Health check:     {CYN('.venv/bin/python installer/doctor.py')}\n")
    return rc


if __name__ == "__main__":
    sys.exit(main())
